### ISSUE TITLE
"channel error" when declaring a queue with RabbitAdmin

### ISSUE THREAD

**Issue by ncoif-tw** [spring-projects/spring-amqp#1035]
Hello!!

The application I'm working on is using Spring-Boot + Spring AMQP and a RabbitMq server for asynchronious events. The queues, exchanges and binding are declared dynamically at runtime, but not as part of the application startup.

Sometimes, declaring such queues fails with the following error, and I have trouble to understand why or to reproduce it with a minimal test case. It seems that these errors started appearing after Spring Boot and Spring AMQP 2.1 migrations. Does this error rings a bell? Any idea on where/what to look for to get more information about this issue? (From my understanding, it seems that it's complaining that the queue does not exists, but as part of the call that is supposed to create this queue?) 

```
2019-06-13 13:52:33,973 redacted-webapp WARN  [org.springframework.amqp.rabbit.listener.BlockingQueueConsumer] Queue declaration failed; retries left=3
org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[redacted-queue-name]
        at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:710)
        at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:594)
        at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:581)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1196)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1041)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: null
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:144)
        at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1006)
        at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:52)
        at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1140)
        at com.sun.proxy.$Proxy254.queueDeclarePassive(Unknown Source)
        at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:689)
        ... 5 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'redacted-queue-name' in vhost '/', class-id=50, method-id=10)
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
        at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
        ... 13 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'redacted-queue-name' in vhost '/', class-id=50, method-id=10)
        at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:516)
        at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
        at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
        at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
        at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:670)
        at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597)
        ... 1 common frames omitted
```

I'm still trying to reproduce the error (I'm hoping to create a minimal test case for it, but so far no luck); the core of the code is using `RabbitListenerEndpointRegistry` and `RabbitAdmin` to declare theses queues, something like:

```
MethodRabbitListenerEndpoint endpoint = ...;
Queue queue = ...;
Exchange exchange = ...;
Binding binding = ...;                  

beanFactory.registerSingleton("consumer_bean_name", endpoint);
beanFactory.registerSingleton("queue_bean_name", queue);
beanFactory.registerSingleton("binding_name", binding);

rabbitAdmin.declareQueue(queue);
rabbitAdmin.declareExchange(exchange);
rabbitAdmin.declareBinding(binding);

rabbitListenerEndpointRegistry.registerListenerContainer(endpoint, rabbitListenerContainerFactory, /* startImmediately */ true);
```

I'm using the following versions:

```spring-boot: 2.1.4.RELEASE
spring-amqp: 2.1.6.RELEASE
spring-rabbit: 2.1.6.RELEASE```

**Comment by garyrussell** [comment]
Please show the queue definition and the `MethodRabbitListenerEndpoint` configuration code.

Unless it's an auto-delete queue, I can't think of any scenario where a successful `declareQueue` can result in that error.

**Comment by ncoif-tw** [comment]
Thanks a lot for looking into it!!!

It seems that our `rabbitAdmin.declareQueue(queue);` was indeed not properly called (we use a custom application health check that disable the queue logic declaration if the application is unhealthy and won't properly handle the events), and that the next call to `rabbitListenerEndpointRegistry.registerListenerContainer` is the one that (rightfully) produced the queue not found error, because the queue was never declared in the first place.

So the problem was in my code. Sorry for the trouble, I'm going to close this one.
