### ISSUE TITLE
Application hangs on shutdown

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-amqp#1103]
**Affects Version(s):**  2.0.10.RELEASE; client 3.6.5

I have a problem with app that will not shutdown - just hangs. I created a thread dump below:

This is a dump

```
"defaultScheduler-9" #63 prio=5 os_prio=0 tid=0x00007f6fa0001000 nid=0x4c6c in Object.wait() [0x00007f6fd6aef000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	- locked <0x000000008331bdc8> (a org.springframework.context.support.AbstractApplicationContext$1)
	at java.lang.Thread.join(Thread.java:1326)
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(Shutdown.java:123)
	at java.lang.Shutdown.sequence(Shutdown.java:167)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- locked <0x0000000083081160> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Runtime.exit(Runtime.java:109)
	at java.lang.System.exit(System.java:971)
	at com.component.package.utils.InactiveComponentRestarter.checkWorking(InactiveComponentRestarter.java:36)
	at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

of this method `(InactiveComponentRestarter.java:36)`

```
@Scheduled(fixedRate = 60_000, initialDelay = 300_000)
  public void checkWorking() {
    LOG.info(
        componentName + " Checking for inactivity, last recorded activity: " + LAST_ACTIVITY.get());
    if (isLastActivityLongerAgoThanInactivityLimit()) {
      LOG.error(
          "Importer has not received any data for "
              + getInactiveTimeThatTriggersRestart() / 1000
              + " seconds , restarting");
      System.exit(1);
    }
  }
```

And I suppose this is the stacktrace of context destroy that is waiting for smth:

```
"Thread-8" #33 prio=5 os_prio=0 tid=0x00007f6fa8013800 nid=0x70f6 in Object.wait() [0x00007f6f977db000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:49)
	- locked <0x00000000ff5ca210> (a com.rabbitmq.utility.BlockingValueOrException)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:88)
	- locked <0x00000000ff5ca210> (a com.rabbitmq.utility.BlockingValueOrException)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:360)
	at com.rabbitmq.client.impl.ChannelN.basicCancel(ChannelN.java:1141)
	at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1032)
	- locked <0x0000000086cfd438> (a java.lang.Object)
	at com.sun.proxy.$Proxy104.basicCancel(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.basicCancel(BlockingQueueConsumer.java:399)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doShutdown(SimpleMessageListenerContainer.java:521)
	- locked <0x0000000086454318> (a java.lang.Object)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.shutdown(AbstractMessageListenerContainer.java:1124)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doStop(AbstractMessageListenerContainer.java:1243)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.stop(AbstractMessageListenerContainer.java:1216)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.stop(AbstractMessageListenerContainer.java:1232)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.stop(RabbitListenerEndpointRegistry.java:263)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:52)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:375)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:211)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1005)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
	- locked <0x000000008331d158> (a java.lang.Object)
```

And all other SIGTERM handlers are blocked by this:

```
"SIGTERM handler" #255 daemon prio=9 os_prio=0 tid=0x00007f7068063800 nid=0xd7a waiting for monitor entry [0x00007f6f941a6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x0000000083081160> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bojanv55** [comment]
OK, now I just checked that this is old version of amqp-client lib, specifically method `basicCancel` is implemented as

```
try {
        k.getReply();
      } catch (ShutdownSignalException var5) {
        throw wrap(var5);
      }
```

while in newer lib it is :

```
try {
        if (this._rpcTimeout == 0) {
          k.getReply();
        } else {
          try {
            k.getReply(this._rpcTimeout);
          } catch (TimeoutException var6) {
            throw this.wrapTimeoutException(m, var6);
          }
        }
      } catch (ShutdownSignalException var7) {
        throw wrap(var7);
      }
```

I guess if I specify rpc timeout this should be resolved then after `this._rpcTimeout` interval?

**Comment by garyrussell** [comment]
Please ask questions about the amqp-client library on the rabbitmq-users Google Group.
