### ISSUE TITLE
java.io.IOException: Unknown consumerTag

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-amqp#1113]
Not sure if this is related to core rabbit java lib or spring, but this is the issue I'm having:

```
java.io.IOException: Unknown consumerTag
at com.rabbitmq.client.impl.ChannelN.basicCancel(ChannelN.java:1476)
at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.basicCancel(PublisherCallbackChannelImpl.java:617)
at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1140)
at com.sun.proxy.$Proxy187.basicCancel(Unknown Source)
at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$InternalConsumer.handleDelivery(BlockingQueueConsumer.java:914)
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)","exception_class":"java.io.IOException","exception_message":"Unknown consumerTag"
```

Received this exception while I was using rabbit 2.0.10, so I tried upgrading to 2.1.10 (just to see if it helps) - but seems that issue is the same. From time to time this thing pops up and I need to restart the service.

This is just graphical view of stacktrace with 2 different versions of rabbit lib.
![image](https://user-images.githubusercontent.com/1422698/67667563-6227b900-f96e-11e9-9975-6065a54ea092.png)

Do you maybe know what could be the problem here?

**Comment by artembilan** [comment]
I think it would be great to explain what the whole situation is around to let us to determine the cause.
Also some simple project with instructions how to reproduce would be really helpful.

And I would like to clean up some things: I believe you talk about Spring AMQP `2.0.10` and `2.1.10`. 
Although there is already `2.0.13` and `2.1.11`...

There is already `2.2.0.RELEASE` for your services. 
Would be great if you can try that one as well.

**Comment by garyrussell** [comment]
The change in 2.1.x was this https://github.com/spring-projects/spring-amqp/pull/936

- Don't call basicCancel if already canceled
- Catch all `Exception`s

There may be some race condition where the consumer is canceled elsewhere.

It does look like we should catch an exception on the cancel though and still go ahead and do the `close()`.

**Comment by bojanv55** [comment]
When are you going to release this version with a fix to maven repo? I just tried it locally and seems it is fixing my issue. The problem actually occurred every time that kubernetes re-scaled pods. Now it seems OK.

**Comment by garyrussell** [comment]
It's currently scheduled for next Monday.
