### ISSUE TITLE
RabbitTemplate proxied by CGLIB results in NPE

### ISSUE THREAD

**Issue by pheyken** [spring-projects/spring-amqp#1140]
[opentracing-contrib/java-spring-rabbitmq](https://github.com/opentracing-contrib/java-spring-rabbitmq) instruments spring-rabbit using aspects and a CGLIB proxy since (I assume) not all methods are defined in the RabbitOperations interface and a RabbitTemplate bean can be autowired directly this way.
Starting an instrumented application prints following info:

```
[      main] INFO     org.springframework.aop.framework.CglibAopProxy - Unable to proxy interface-implementing method [public final void org.springframework.amqp.rabbit.core.RabbitTemplate.start()] because it is marked as final: Consider using interface-based JDK proxies instead!
[      main] INFO     org.springframework.aop.framework.CglibAopProxy - Unable to proxy interface-implementing method [public final void org.springframework.amqp.rabbit.core.RabbitTemplate.stop()] because it is marked as final: Consider using interface-based JDK proxies instead!
```

When the application is shutdown, a NPE is thrown:

```
[      main] WARN  ramework.context.support.DefaultLifecycleProcessor - Failed to stop bean 'rabbitTemplate'
java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.core.RabbitTemplate.stop(RabbitTemplate.java:902)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:251)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1018)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:975)
	at org.springframework.test.context.cache.DefaultContextCache.remove(DefaultContextCache.java:207)
	at org.springframework.test.context.cache.DefaultContextCache.remove(DefaultContextCache.java:172)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.closeContext(DefaultCacheAwareContextLoaderDelegate.java:144)
	at org.springframework.test.context.support.DefaultTestContext.markApplicationContextDirty(DefaultTestContext.java:132)
	at org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener.dirtyContext(AbstractDirtiesContextTestExecutionListener.java:69)
	at org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener.beforeOrAfterTestClass(AbstractDirtiesContextTestExecutionListener.java:148)
	at org.springframework.test.context.support.DirtiesContextTestExecutionListener.afterTestClass(DirtiesContextTestExecutionListener.java:96)
	at org.springframework.test.context.TestContextManager.afterTestClass(TestContextManager.java:490)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Log messages are taken from the [opentracing-contrib/java-spring-rabbitmq](https://github.com/opentracing-contrib/java-spring-rabbitmq) integration tests, same behavior for normal application launches / stops

I see two possible solutions. Either changing the `stop()` (and `start()`) method(s) to be non-final or adding the missing methods that are instrumented by [opentracing-contrib/java-spring-rabbitmq](https://github.com/opentracing-contrib/java-spring-rabbitmq) to the RabbitOperations interface and changing the proxy method to JDK-based.

I feel like it would be simpler to make the methods non-final and continue using CGLIB, because changing to JDK-based proxy would mean that the RabbitTemplate cannot be autowired directly anymore, but only the interface.

**Comment by garyrussell** [comment]
Thanks; I think we should do both; it's always preferable to reference using the interface.

Please confirm which version(s) you are using; I currently only plan to do this in 2.3.x but can backport if needed.

**Comment by pheyken** [comment]
Mostly 2.1.x right now, but backport is not needed. Thank you!

**Comment by garyrussell** [comment]
Sorry, I meant 2.2.x not 2.3.x (too many projects) - 2.2.3 will be released next week.
