### ISSUE TITLE
AsyncRabbitTemplate is blocking

### ISSUE THREAD

**Issue by lfmunoz** [spring-projects/spring-amqp#1151]
I am trying to make an async call to send and receive a rabbit message but call convertSendAndReceive is blocking.

The problem line is here:

https://github.com/spring-projects/spring-amqp/blob/028550cf7fcf6eacf3063b746414151c1ccb2117/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/AsyncRabbitTemplate.java#L478

That method has a synchronize and therefore can block

I am actually using spring-rabbit-2.1.7.RELEASE but the problem seems also be in master as shown above.

Doing an async call like this:
```
    authAsyncTemplate.convertSendAndReceive<AuthenticationResponse>(AUTH_REQUEST_EXCHANGE, "", request)
                .addCallback(object : ListenableFutureCallback<AuthenticationResponse> {
                    override fun onFailure(ex: Throwable) {
                        cont.resumeWithException(ex)
                    }
                    override fun onSuccess(result: AuthenticationResponse?) {
                        if (result!!.status == AuthenticationStatus.OK) {
                            cont.resume(result.destinationPatterns)
                        } else {
                            val authResult = AuthenticationFailedException(result.message)
                            cont.resumeWithException(authResult)
                        }
                    }
                })
```

## Stack trace 1

```
been blocked for 3165 ms, time limit is 2000 ms
2020-01-29 20:34:14.441  WARN 16914 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3164 ms, time limit is 2000 ms
2020-01-29 20:34:15.441  WARN 16914 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 4167 ms, time limit is 2000 ms
2020-01-29 20:34:15.441  WARN 16914 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 4166 ms, time limit is 2000 ms
2020-01-29 20:34:15.441  WARN 16914 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4165 ms, time limit is 2000 ms
2020-01-29 20:34:16.443  WARN 16914 --- [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  : Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 5167 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
    at java.lang.Object.wait(Native Method)
    at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:73)
    at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
    at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
    at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
    at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
    at com.rabbitmq.client.impl.ChannelN.basicQos(ChannelN.java:644)
    at com.rabbitmq.client.impl.ChannelN.basicQos(ChannelN.java:660)
    at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1140)
    at com.sun.proxy.$Proxy114.basicQos(Unknown Source)
    at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.consume(DirectMessageListenerContainer.java:699)
    at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.doConsumeFromQueue(DirectMessageListenerContainer.java:677)
    at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.adjustConsumers(DirectMessageListenerContainer.java:313)
    at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.setConsumersPerQueue(DirectMessageListenerContainer.java:161)
    at org.springframework.amqp.rabbit.listener.DirectReplyToMessageListenerContainer.getChannelHolder(DirectReplyToMessageListenerContainer.java:190)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:477)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:418)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:399)
    at eco.usp.proxy.stomp.OurConnectHandler.sendAuthReq$suspendImpl(OurConnectHandler.kt:148)
    at eco.usp.proxy.stomp.OurConnectHandler.sendAuthReq(OurConnectHandler.kt)
    at eco.usp.proxy.stomp.OurConnectHandler.authenticate$suspendImpl(OurConnectHandler.kt:112)
    at eco.usp.proxy.stomp.OurConnectHandler.authenticate(OurConnectHandler.kt)
    at eco.usp.proxy.stomp.OurStompHandler$handleConnect$1.invokeSuspend(OurStompHandler.kt:234)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:230)
    at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
    at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:413)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
    at eco.usp.proxy.stomp.OurStompHandler.handleConnect(OurStompHandler.kt:233)
    at eco.usp.proxy.stomp.OurStompHandler.handle(OurStompHandler.kt:129)
    at eco.usp.proxy.stomp.OurStompHandler.handle(OurStompHandler.kt:60)
    at eco.usp.proxy.vertx.OurStompServerImpl$listen$3$4.handle(OurStompServerImpl.kt:125)
    at eco.usp.proxy.vertx.OurStompServerImpl$listen$3$4.handle(OurStompServerImpl.kt:48)
    at io.vertx.ext.stomp.impl.FrameParser.handleLine(FrameParser.java:164)
    at io.vertx.ext.stomp.impl.FrameParser$$Lambda$816/2079949477.handle(Unknown Source)
    at io.vertx.core.parsetools.impl.RecordParserImpl.handleParsing(RecordParserImpl.java:197)
    at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:259)
    at io.vertx.ext.stomp.impl.FrameParser.handle(FrameParser.java:221)
    at io.vertx.ext.stomp.impl.FrameParser.handle(FrameParser.java:35)
    at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:386)
    at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
    at io.vertx.core.net.impl.NetSocketImpl$$Lambda$810/981838059.handle(Unknown Source)
    at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:235)
    at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:125)
    at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:364)
    at io.vertx.core.net.impl.VertxHandler$$Lambda$811/2047067999.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:417)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:317)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)


```

## Stack trace 2

```

io.vertx.core.VertxException: Thread blocked
    at org.springframework.amqp.rabbit.listener.DirectReplyToMessageListenerContainer.getChannelHolder(DirectReplyToMessageListenerContainer.java:173)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:477)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:418)
    at org.springframework.amqp.rabbit.AsyncRabbitTemplate.convertSendAndReceive(AsyncRabbitTemplate.java:399)
    at eco.usp.proxy.stomp.OurConnectHandler.sendAuthReq$suspendImpl(OurConnectHandler.kt:148)
    at eco.usp.proxy.stomp.OurConnectHandler.sendAuthReq(OurConnectHandler.kt)
    at eco.usp.proxy.stomp.OurConnectHandler.authenticate$suspendImpl(OurConnectHandler.kt:112)
    at eco.usp.proxy.stomp.OurConnectHandler.authenticate(OurConnectHandler.kt)
    at eco.usp.proxy.stomp.OurStompHandler$handleConnect$1.invokeSuspend(OurStompHandler.kt:234)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:230)
    at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
    at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:413)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
    at eco.usp.proxy.stomp.OurStompHandler.handleConnect(OurStompHandler.kt:233)
    at eco.usp.proxy.stomp.OurStompHandler.handle(OurStompHandler.kt:129)
    at eco.usp.proxy.stomp.OurStompHandler.handle(OurStompHandler.kt:60)
    at eco.usp.proxy.vertx.OurStompServerImpl$listen$3$4.handle(OurStompServerImpl.kt:125)
    at eco.usp.proxy.vertx.OurStompServerImpl$listen$3$4.handle(OurStompServerImpl.kt:48)
    at io.vertx.ext.stomp.impl.FrameParser.handleLine(FrameParser.java:164)
    at io.vertx.ext.stomp.impl.FrameParser$$Lambda$816/2079949477.handle(Unknown Source)
    at io.vertx.core.parsetools.impl.RecordParserImpl.handleParsing(RecordParserImpl.java:197)
    at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:259)
    at io.vertx.ext.stomp.impl.FrameParser.handle(FrameParser.java:221)
    at io.vertx.ext.stomp.impl.FrameParser.handle(FrameParser.java:35)
    at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:386)
    at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
    at io.vertx.core.net.impl.NetSocketImpl$$Lambda$810/981838059.handle(Unknown Source)
    at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:235)
    at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:125)
    at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:364)
    at io.vertx.core.net.impl.VertxHandler$$Lambda$811/2047067999.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:417)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:317)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)







```

**Comment by garyrussell** [comment]
The async template makes no claims to be non-blocking since the underlying amqp-client is not.

I am not sure what you mean by 

>That method has a synchronize and therefore can block

There is no synchronization there.

The `getChannelHolder()` is blocked on `consumersMonitor` which is held by your first thread.

I am not sure why that thread is blocked on `basicQos()`...

```
    at java.lang.Object.wait(Native Method)
    at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:73)
    at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
    at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
    at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
    at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
    at com.rabbitmq.client.impl.ChannelN.basicQos(ChannelN.java:644)
    at com.rabbitmq.client.impl.ChannelN.basicQos(ChannelN.java:660)
```

...that would be a question for the RabbitMQ engineers on the rabbitmq-users Google group.

**Comment by lfmunoz** [comment]
Thanks for the response, I suppose there is nothing you can do here. I thought this call was suppose to be guaranteed to be non-blocking since it has the name async which to me implies non-blocking. You can close this.

**Comment by garyrussell** [comment]
The async return type simply means we don't block waiting for a reply; we have no control over the client when sending.
