### ISSUE TITLE
Broken pipe (Write failed)

### ISSUE THREAD

**Issue by ZShUn** [spring-projects/spring-amqp#1180]
The following abnormality occurs when the pressure data is 150W

Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at java.io.DataOutputStream.writeByte(DataOutputStream.java:153)
        at com.rabbitmq.client.impl.Frame.writeTo(Frame.java:185)
        at com.rabbitmq.client.impl.SocketFrameHandler.writeFrame(SocketFrameHandler.java:171)
        at com.rabbitmq.client.impl.AMQConnection.writeFrame(AMQConnection.java:551)
        at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:104)
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:447)
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:423)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:685)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:667)
        at org.springframework.amqp.rabbit.support.PublisherCallbackChannelImpl.basicPublish(PublisherCallbackChannelImpl.java:199)
        at sun.reflect.GeneratedMethodAccessor828.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:991)
        at com.sun.proxy.$Proxy155.basicPublish(Unknown Source)
        at org.springframework.amqp.rabbit.core.RabbitTemplate.sendToRabbit(RabbitTemplate.java:1998)
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doSend(RabbitTemplate.java:1986)
        at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$send$3(RabbitTemplate.java:860)
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1828)
        ... 14 more

**Comment by garyrussell** [comment]
Most likely it's some kind of network problem.

This has nothing to do with Spring or this project; you should ask such questions on the rabbitmq-users Google Group.

I suggest you look in the server log to see if there are any clues there.
