### ISSUE TITLE
 Throws NullPointerException if I use BatchMessagingMessageListenerAdapter

### ISSUE THREAD

**Issue by ShambuGIT** [spring-projects/spring-amqp#1207]
https://github.com/spring-projects/spring-amqp/blob/6c134537af7e16066394d517245bf3fd44fc3f79/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/adapter/MessagingMessageListenerAdapter.java#L144

My code to for batchMessage. Let me know if this is not a correct way to create BatchMessagingMessageListenerAdapter for my project.
```java
public class CustomBatchMessagingMessageListenerAdapter extends BatchMessagingMessageListenerAdapter {

	private final static String defaultMethodName = "handleMessages";
	
    public CustomBatchMessagingMessageListenerAdapter(Object bean, Method method, MessageConverter messageConverter)
    {
        super(bean, null, false, null, null);
        setMessageConverter(messageConverter);
        HandlerAdapter adapter = createHandleAdapter(bean, method);
        setHandlerAdapter(adapter);
    }

    public CustomBatchMessagingMessageListenerAdapter(Object bean, MessageConverter messageConverter)
    {
        this(bean, BeanUtils.findDeclaredMethodWithMinimalParameters(bean.getClass(), defaultMethodName),
                messageConverter);
    }

    private HandlerAdapter createHandleAdapter(Object bean, Method method)
    {
        MessageHandlerMethodFactory messageHandlerMethodFactory = new DefaultMessageHandlerMethodFactory();
        InvocableHandlerMethod invokerHandlerMethod = messageHandlerMethodFactory.createInvocableHandlerMethod(bean,
                method);

        HandlerMethodArgumentResolverComposite resolvers = new HandlerMethodArgumentResolverComposite();
        resolvers.addResolver(
                new org.springframework.messaging.handler.annotation.support.HeadersMethodArgumentResolver());
        resolvers.addResolver(
                new org.springframework.messaging.handler.annotation.support.MessageMethodArgumentResolver());
        resolvers
                .addResolver(new org.springframework.messaging.handler.annotation.support.PayloadMethodArgumentResolver(
                        new GenericMessageConverter()));
        invokerHandlerMethod.setMessageMethodArgumentResolvers(resolvers);
        HandlerAdapter handler = new HandlerAdapter(invokerHandlerMethod);
        return handler;
    }
}
```

**Comment by garyrussell** [comment]
Please add the stack trace.

**Comment by ShambuGIT** [comment]
Below is the stack trace.

org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1690) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1583) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1498) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1481) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.executeWithList(SimpleMessageListenerContainer.java:1023) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1012) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190) [spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: org.springframework.amqp.UncategorizedAmqpException: java.lang.NullPointerException
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:82) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.adapter.BatchMessagingMessageListenerAdapter.onMessageBatch(BatchMessagingMessageListenerAdapter.java:83) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1575) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:145) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.amqp.rabbit.listener.adapter.BatchMessagingMessageListenerAdapter.onMessageBatch(BatchMessagingMessageListenerAdapter.java:80) ~[spring-rabbit-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	... 12 common frames omitted

**Comment by garyrussell** [comment]
That implies the `handlerAdapter` field is `null`, but I see you are setting it.

Can you run it in a debugger to see what's happening?

**Comment by ShambuGIT** [comment]
As I tagged in the issue, NPE is throwing in line numer 145 in MessagingMessageListenerAdapter.java(highlighted below) when the batch consume message is enabled. 
if (this.messagingMessageConverter.method == null) {
		**amqpMessage**.getMessageProperties()
						.setTargetMethod(this.handlerAdapter.getMethodFor(message.getPayload()));
			}

Since we have enabled batch messaging the amqpMessage will be null and "Message<?> message" will be non null as it is called like that from BatchMessagingMessageListenerAdapter.onMessageBatch line number 80.

**Comment by garyrussell** [comment]
So, the problem is here

`super(bean, null, false, null, null);`

You are setting `method` to `null`; hence NPE; pass the `method` in.

**Comment by ShambuGIT** [comment]
Yes, but why should i set my handler method in both MessagingMessageConverterAdapter and HandleAdapter class. When I debug it looks this does not serve any purpose other than skipping this NPE and determining the inferredArgumentType in MessagingMessageConverterAdapter. Another  side effect observed is, Json conversion is not happening if the bean class is created from spring proxy class.  It fails to determine the correct inferredArgumentType(java.util List instead of java.lang.Object) in MessagingMessageConverterAdapter if my bean method argument is List<Message>. 
 
It feels me this implementation too complex compare to MessageListenerAdapter which is used for single message.   Any easy way to plugin this adapter would be much helpful for batch processing.

**Comment by garyrussell** [comment]
I am not saying the NPE shouldn't be fixed, but it will get past the problem for you.

We did not anticipate people subclassing this class.

I am not sure what you mean about proxies; I see no problems (in the superclass inferring the parameter type) both with JDK and CGLIB proxies:

```java
@SpringBootApplication
public class Rgh1207Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1207Application.class, args);
	}

	@Bean
	public Foo foo() {
		ProxyFactory pf = new ProxyFactory(new Foo());
		pf.setProxyTargetClass(true);
		return (Foo) pf.getProxy();
	}

	@Bean
	public Bar bar() {
		ProxyFactory pf = new ProxyFactory(new Foo());
		return (Bar) pf.getProxy();
	}

}

class Foo implements Bar {

	@Override
	@RabbitListener(queues = "foo")
	public void listen(List<String> in) {

	}

}

interface Bar {

	void listen(List<String> in);

}
```

In both cases, the parameter is correctly determined to be `List<String>`.

You are overriding the default converter and bypassing the type inference.
