### ISSUE TITLE
AbstractMessageListenerContainer.buildTimer() throws NullPointerException when listenerId is null

### ISSUE THREAD

**Issue by pkthoo** [spring-projects/spring-amqp#1214]
**Affects Version(s):** \<spring-rabbit v2.2.6.RELEASE>

---

**Stack trace:**
```
18:14:58.178 [syncTaskExecutor-663] DEBUG o.s.a.r.l.SimpleMessageListenerContainer - Consumer raised exception, processing can restart if the connection factory supports it
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:35)
	at io.micrometer.core.instrument.Tag.of(Tag.java:29)
	at io.micrometer.core.instrument.Tags.and(Tags.java:74)
	at io.micrometer.core.instrument.Timer$Builder.tag(Timer.java:364)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$MicrometerHolder.buildTimer(AbstractMessageListenerContainer.java:2040)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$MicrometerHolder.failure(AbstractMessageListenerContainer.java:2031)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1430)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:963)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190)
	at java.lang.Thread.run(Thread.java:748)
```

**Observed behavior:**
MessageListener - receiving the same queued message repeatedly (~5/sec)
Log file - repeatedly logged the following (also ~5/sec)

- '... SimpleMessageListenerContainer - Restarting Consumer@...'
- '... SimpleMessageListenerContainer - Failed to check/redeclare auto-delete queue(s).'

**Severity:**
[Very Severe] because application is being spammed by the same message in queue

**Workaround:**
Set a valid String in SimpleRabbitListenerEndpoint.setId() 

**Code:**
```java
    @Autowired
    SimpleRabbitListenerContainerFactory listenerContainerFactory;
	
    @PostConstruct
    public void init() {
	    final Logger log = getLogger();
        final String queueName = "MaterialOrders";
		
        MessageListener messageListener = message -> {
            try {
				log.info("[{}] <<< {}", queueName, new String(message.getBody()));
			} catch (Throwable t) {
			    log.error("[{}]", queueName, t);
			}
        };


        SimpleRabbitListenerEndpoint endpoint = new SimpleRabbitListenerEndpoint();
        endpoint.setMessageListener(messageListener);
        endpoint.setQueueNames(queueName);
        
		// UNCOMMENT TO WORKAROUND THE REPORTED ISSUE
		// endpoint.setId("{"+System.currentTimeMillis()+"}");

        SimpleMessageListenerContainer container = listenerContainerFactory.createListenerContainer(endpoint);
        container.start();
    }
```

**Comment by garyrussell** [comment]
Can you show the full stack trace? I can't reproduce it.

```java
@SpringBootApplication
public class Rgh1214Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1214Application.class, args);
	}


	@Bean
	public ApplicationRunner runner(RabbitListenerContainerFactory<SimpleMessageListenerContainer> factory) {
		return args -> {
			SimpleRabbitListenerEndpoint ep = new SimpleRabbitListenerEndpoint();
			ep.setMessageListener(msg -> {
				System.out.println(msg);
			});
			ep.setQueueNames("q1");
			SimpleMessageListenerContainer container = factory.createListenerContainer(ep);
			container.start();
		};
	}
}
```

Also

>container.start();

You should not start containers in `@PostConstruct` - it's too early.

**Comment by pkthoo** [comment]
A snippet of my log file:
[amqp.log](https://github.com/spring-projects/spring-amqp/files/4810931/amqp.log)

My code:
[AmqpIssue_2020_06_09.java.txt](https://github.com/spring-projects/spring-amqp/files/4810970/AmqpIssue_2020_06_09.java.txt)
