### ISSUE TITLE
[Backward Compatibility] UnableToRegisterMBeanException: Unable to register MBean SimpleMessageListenerContainer

### ISSUE THREAD

**Issue by ankushgats** [spring-projects/spring-amqp#1264]
https://github.com/spring-projects/spring-amqp/blob/e2414fadb76ef85ea93858e32dd07899fb37e705/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L454
With new spring upgrade, from 2.1.x to 2.2.x, I started facing problem while startup the spring container having rabbit message listeners bean definitions.
We are getting error:
```

Caused by: javax.management.IntrospectionException: type mismatch between getter and setter
	at javax.management.MBeanAttributeInfo.attributeType(MBeanAttributeInfo.java:341)
	at javax.management.MBeanAttributeInfo.<init>(MBeanAttributeInfo.java:185)
	at javax.management.modelmbean.ModelMBeanAttributeInfo.<init>(ModelMBeanAttributeInfo.java:202)
	at org.springframework.jmx.export.assembler.AbstractReflectiveMBeanInfoAssembler.getAttributeInfo(AbstractReflectiveMBeanInfoAssembler.java:320)
	at org.springframework.jmx.export.assembler.AbstractMBeanInfoAssembler.getMBeanInfo(AbstractMBeanInfoAssembler.java:67)
	at org.springframework.jmx.export.MBeanExporter.getMBeanInfo(MBeanExporter.java:847)
	at org.springframework.jmx.export.MBeanExporter.createAndConfigureMBean(MBeanExporter.java:820)
```
on investigating I found that `public void setMessageListener(Object messageListener)` is removed, but the getMessageListener method still returns value of type 'Object' and MBeanAttributeInfo class finds mismatch in setter parameter type and getter return type and thus fails to startup the spring container.
Now that we have only setMessageListener(MessageListener) method to set message listener why can't we force getMessageListener to return MessageListener instead of Object?

**Comment by ankushgats** [comment]
Created PR for this issue: https://github.com/spring-projects/spring-amqp/pull/1265

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-amqp/pull/1265
