### ISSUE TITLE
Queue not automatically re-created with multiple connection factories

### ISSUE THREAD

**Issue by cossementkristof** [spring-projects/spring-amqp#1327]
When deleting a queue in RabbitMQ, the connected client re-creates the queue and re-connects.
When restarting the RabbitMQ server, also the connection to that queue is re-established:

<pre>

@Configuration
public class AmqpConfig1 {

    private String host = "127.0.0.1";

    private String username = "guest";

    private String password = "guest";

    private Integer port = 5672;

    private String queueName = "queue1";

    @Bean
    RabbitAdmin rabbitAdmin1(ConnectionFactory connectionFactory1) {
        return new RabbitAdmin(connectionFactory1);
    }

    @Bean
    ConnectionFactory connectionFactory1() {
        CachingConnectionFactory connectionFactory = new CachingConnectionFactory(host, port);
        connectionFactory.setUsername(username);
        connectionFactory.setPassword(password);
        return connectionFactory;
    }

    @Bean
    Exchange exchange1(RabbitAdmin rabbitAdmin1) {
        return ExchangeBuilder.directExchange("exchange1")
                .durable(true)
                .admins(rabbitAdmin1)
                .build();
    }

    @Bean
    Queue queue1(RabbitAdmin rabbitAdmin1) {
        Queue queue = QueueBuilder.durable(queueName).build();
        queue.setAdminsThatShouldDeclare(rabbitAdmin1);
        return queue;
    }

    @Bean
    Binding queueBinding1(
            Queue queue1, Exchange exchange1, RabbitAdmin rabbitAdmin1) {
        Binding binding = BindingBuilder.bind(queue1).to(exchange1).with("route1").noargs();
        binding.setAdminsThatShouldDeclare(rabbitAdmin1);
        return binding;
    }

    @Bean
    MessageListenerAdapter queueListenerAdapter1(MyListener myListener) {
        return new MessageListenerAdapter(myListener);
    }

    @Bean
    DirectMessageListenerContainer queueContainer1(
            ConnectionFactory connectionFactory1,
            MessageListenerAdapter queueListenerAdapter1) {

        DirectMessageListenerContainer container = new DirectMessageListenerContainer();
        container.setConnectionFactory(connectionFactory1);
        container.setQueueNames(queueName);
        container.setMessageListener(queueListenerAdapter1);
        return container;
    }
</pre>

### When configuring multiple ConnectionFactory's (and rabbitAdmin) in spring configuration, queue's are not being re-created anymore, but an IOException occurs:

<pre>

@Configuration
public class AmqpConfig2 {

    private String host = "127.0.0.1";

    private String username = "guest";

    private String password = "guest";

    private Integer port = 5672;

    private String queueName = "queue2";

    @Bean
    RabbitAdmin rabbitAdmin2(ConnectionFactory connectionFactory2) {
        return new RabbitAdmin(connectionFactory2);
    }

    @Bean
    ConnectionFactory connectionFactory2() {
        CachingConnectionFactory connectionFactory = new CachingConnectionFactory(host, port);
        connectionFactory.setUsername(username);
        connectionFactory.setPassword(password);
        return connectionFactory;
    }

</pre>

<pre>
2021-04-23 09:47:44.701 ERROR 18492 --- [pool-1-thread-4] o.s.a.r.l.DirectMessageListenerContainer : Consumer canceled - queue deleted? SimpleConsumer [queue=queue1, index=0, consumerTag=amq.ctag-14IVi7qXm77CGSXwl1xGgw identity=440966a9]
2021-04-23 09:47:48.908 ERROR 18492 --- [nsumerMonitor-1] o.s.a.r.l.DirectMessageListenerContainer : Queue not present, scheduling consumer SimpleConsumer [queue=queue1, index=0, consumerTag=null identity=724437a] for restart
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46) ~[amqp-client-5.10.0.jar:5.10.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1157) ~[spring-rabbit-2.3.6.jar:2.3.6]
	at com.sun.proxy.$Proxy62.queueDeclarePassive(Unknown Source) ~[na:na]
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.consume(DirectMessageListenerContainer.java:741) ~[spring-rabbit-2.3.6.jar:2.3.6]
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.doConsumeFromQueue(DirectMessageListenerContainer.java:709) ~[spring-rabbit-2.3.6.jar:2.3.6]
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.restartConsumer(DirectMessageListenerContainer.java:551) ~[spring-rabbit-2.3.6.jar:2.3.6]
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer.lambda$startMonitor$5(DirectMessageListenerContainer.java:481) ~[spring-rabbit-2.3.6.jar:2.3.6]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.6.jar:5.3.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'queue1' in vhost '/', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141) ~[amqp-client-5.10.0.jar:5.10.0]
	... 19 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'queue1' in vhost '/', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:517) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:341) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47) ~[amqp-client-5.10.0.jar:5.10.0]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666) ~[amqp-client-5.10.0.jar:5.10.0]
	... 1 common frames omitted
</pre>

This is also the case when RabbitMQ server is being shutdown and restarted with all queue's removed (eg. when docker volume where rabbitmq is persisted is cleared).
Our use case is to connect to 2 different RabbitMQ servers, but it is also reproducible connecting to the same RabbitMQ Server.

Steps to reproduce: 

- Start RabbitMQ server on localhost
- Start springboot project (creates 2 exchanges and queue's)
- Delete queue1 
- Exception occured

Repeat with configuration of only 1 AmqpConfig -> then you see no exceptions occur and queue is re-created and re-connected to.

Example zip file contains simple project with 2 Connection Factory's defined.
Code to reproduce: [issue_1327.zip](https://github.com/spring-projects/spring-amqp/files/6363697/issue_1327.zip)

**Comment by garyrussell** [comment]
The container will only try to redeclare a queue if there is only one admin in the application context. For this use case, you need to tell each container which admin to use:

```java
    @Bean
    DirectMessageListenerContainer queueContainer1(
            ConnectionFactory connectionFactory1,
            MessageListenerAdapter queueListenerAdapter1,
            RabbitAdmin rabbitAdmin1) {

        DirectMessageListenerContainer container = new DirectMessageListenerContainer();
        container.setConnectionFactory(connectionFactory1);
        container.setQueueNames(queueName);
        container.setMessageListener(queueListenerAdapter1);
        container.setAmqpAdmin(rabbitAdmin1);
        return container;
    }
```

**Comment by cossementkristof** [comment]
Thanks, works !
