### ISSUE TITLE
NullPointerException in org.springframework.amqp.rabbit.connection.AbstractConnectionFactory during shutdown of SpringBoot application

### ISSUE THREAD

**Issue by maecval** [spring-projects/spring-amqp#1450]
**In what version(s) of Spring AMQP are you seeing this issue?**

2.4.2

**Describe the bug**

During the shutdown of the SpringBoot application the following NullPointerException gets thrown/logged:
```
2022-04-13 06:44:45.077 WARN  [o.s.c.a.AnnotationConfigApplicationContext] (SpringApplicationShutdownHook) Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.onApplicationEvent(AbstractConnectionFactory.java:215)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.onApplicationEvent(AbstractConnectionFactory.java:72)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:427)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:96)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:212)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:137)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**

Shut down of SpringBoot application.

**Expected behavior**

No NullPointerException shall be thrown/logged in this case.
This can be achieved by fixing the code of class [AbstractConnectionFactory](https://github.com/spring-projects/spring-amqp/blob/57bc30fe5d3923e6bee03657bc5cae19572cf69f/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java#L215)
The following shows the fixed `if`statement of method: [public void onApplicationEvent(ContextClosedEvent event)](https://github.com/spring-projects/spring-amqp/blob/57bc30fe5d3923e6bee03657bc5cae19572cf69f/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java#L214)

```
	@Override
	public void onApplicationEvent(ContextClosedEvent event) {
		if (getApplicationContext() != null && getApplicationContext().equals(event.getApplicationContext())) {
			this.contextStopped = true;
		}
		if (this.publisherConnectionFactory != null) {
			this.publisherConnectionFactory.onApplicationEvent(event);
		}
	}
```
It adds `getApplicationContext() != null && ` to the `if`statement.

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-amqp/pull/1451

in 2.4.4 and 2.3.16
