### ISSUE TITLE
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: No correlation header in reply

### ISSUE THREAD

**Issue by marcosstefani** [spring-projects/spring-amqp#1548]
In what version(s) of Spring AMQP are you seeing this issue? 
2.4.7

**Describe the bug**

I'm trying to migrate the spring boot parent and I had the displeasure of starting to receive an error message when trying to consume the messages. The error is the title, and this occurred when trying to update the spring parent.

obs. Service queues are not request reply queues

Previous:

org.springframework.amqp:spring-boot-starter-web:jar:2.4.3
org.springframework.boot:spring-boot-starter-amqp:jar:2.4.3
org.springframework.amqp:spring-amqp:jar:2.3.5

After with problem:
org.springframework.boot:spring-boot-starter-web:jar:2.7.5
org.springframework.boot:spring-boot-starter-amqp:jar:2.7.5
org.springframework.amqp:spring-amqp:jar:2.4.7

Error:
```
2022-12-26 11:28:12.175 [notificationsContainer-1] WARN  o.s.a.r.l.ConditionalRejectingErrorHandler - Execution of Rabbit message listener failed.
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1771) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1661) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1576) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1564) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1555) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1499) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:992) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:939) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:84) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1316) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1222) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: No correlation header in reply
    at org.springframework.amqp.rabbit.core.RabbitTemplate.onMessage(RabbitTemplate.java:2663) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:273) ~[spring-rabbit-2.4.5.jar:2.4.5]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1657) ~[spring-rabbit-2.4.5.jar:2.4.5]
    ... 10 common frames omitted

```

**To Reproduce**

Configure a Config with follow code and try to send any message.

**Expected behavior**

As I'm not setting up any reploy requests, I expect the message to be read normally from an implementation of `ChannelAwareMessageListener`

**Sample**

```
@Configuration
@RequiredArgsConstructor
public class MessageQueueConfiguration {
    private static final String BROKER_NOTIFICATIONS = "notifications";
    private static final String BROKER_USERS = "users";
    private static final String BROKER_ADMIN = "admin";
    private static final String BROKER_REPORTS = "reports";

    private final MessageQueueProperties messageQueueProperties;
    private final BrokerProperties brokerProperties;
    private final ObjectMapper objectMapper;

    @Bean
    public AmqpAdmin brokerUsersAmqpAdmin(@Qualifier("brokerUsersConnectionFactory") ConnectionFactory brokerUsersConnectionFactory) {
        return getAmqpAdmin(brokerUsersConnectionFactory);
    }

    @Bean
    public AmqpAdmin brokerAdminAmqpAdmin(@Qualifier("brokerAdminConnectionFactory") ConnectionFactory brokerAdminConnectionFactory) {
        return getAmqpAdmin(brokerAdminConnectionFactory);
    }

    @Bean
    public AmqpAdmin brokerNotificationsAmqpAdmin(@Qualifier("brokerNotificationsConnectionFactory") ConnectionFactory brokerNotificationsConnectionFactory) {
        return getAmqpAdmin(brokerNotificationsConnectionFactory);
    }

    @Bean
    public AmqpAdmin brokerReportsAmqpAdmin(@Qualifier("brokerReportsConnectionFactory") ConnectionFactory brokerReportsConnectionFactory) {
        return getAmqpAdmin(brokerReportsConnectionFactory);
    }

    @Bean
    public MessageListenerAdapter listenerMessageQueueAdapter(ChannelAwareMessageListener messageBrokerReceiver) {
        return new MessageListenerAdapter(messageBrokerReceiver);
    }

    @Bean
    public CachingConnectionFactory brokerNotificationsConnectionFactory() {
        return createCachingConnectionFactory(BROKER_NOTIFICATIONS);
    }

    @Bean
    public CachingConnectionFactory brokerUsersConnectionFactory() {
        return createCachingConnectionFactory(BROKER_USERS);
    }

    @Bean
    public CachingConnectionFactory brokerAdminConnectionFactory() {
        return createCachingConnectionFactory(BROKER_ADMIN);
    }

    @Bean
    public CachingConnectionFactory brokerReportsConnectionFactory() {
        return createCachingConnectionFactory(BROKER_REPORTS);
    }

    @Bean
    public SimpleMessageListenerContainer notificationsContainer(@Qualifier("brokerNotificationsConnectionFactory") ConnectionFactory connectionFactory, MessageListenerAdapter messageListenerAdapter) {
        return createMessageListenerContainer(connectionFactory, messageListenerAdapter);
    }

    @Bean
    public SimpleMessageListenerContainer usersContainer(@Qualifier("brokerUsersConnectionFactory") ConnectionFactory connectionFactory, MessageListenerAdapter messageListenerAdapter) {
        return createMessageListenerContainer(connectionFactory, messageListenerAdapter);
    }

    @Bean
    public SimpleMessageListenerContainer adminContainer(@Qualifier("brokerAdminConnectionFactory") ConnectionFactory connectionFactory, MessageListenerAdapter messageListenerAdapter) {
        return createMessageListenerContainer(connectionFactory, messageListenerAdapter);
    }

    @Bean
    public SimpleMessageListenerContainer reportsContainer(@Qualifier("brokerReportsConnectionFactory") ConnectionFactory connectionFactory, MessageListenerAdapter messageListenerAdapter) {
        return createMessageListenerContainer(connectionFactory, messageListenerAdapter);
    }

    private SimpleMessageListenerContainer createMessageListenerContainer(ConnectionFactory connectionFactory, MessageListenerAdapter messageListenerAdapter){
        SimpleMessageListenerContainer container = new SimpleMessageListenerContainer();

        container.setConnectionFactory(connectionFactory);
        container.setQueueNames(
                messageQueueProperties.getQueue1(),
                messageQueueProperties.getQueue2(),
                messageQueueProperties.getQueue3(),
                messageQueueProperties.getQueue4(),
                messageQueueProperties.getQueue5(),
                messageQueueProperties.getQueue6(),
                messageQueueProperties.getQueue7()
        );
        container.setMessageListener(messageListenerAdapter);
        container.setMaxConcurrentConsumers(50);
        container.setAcknowledgeMode(AcknowledgeMode.MANUAL);
        container.setMissingQueuesFatal(false);
        container.setFailedDeclarationRetryInterval(60000);

        return container;
    }

    private CachingConnectionFactory createCachingConnectionFactory(String brokerName) {
        CachingConnectionFactory cachingConnectionFactory = new CachingConnectionFactory(
                brokerProperties.getBrokers().get(brokerName).getHost(),
                brokerProperties.getBrokers().get(brokerName).getPort());
        cachingConnectionFactory.setUsername(brokerProperties.getBrokers().get(brokerName).getUsername());
        cachingConnectionFactory.setPassword(brokerProperties.getBrokers().get(brokerName).getPassword());
        cachingConnectionFactory.setConnectionTimeout(brokerProperties.getBrokers().get(brokerName).getTimeout());
        return cachingConnectionFactory;
    }

    private Queue queue1() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getEmailQueueName(), true, false, false, queueArguments);
    }

    private Queue queue2() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getIosPushQueueName(), true, false, false, queueArguments);
    }

    private Queue queue3() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getContentCardQueueName(), true, false, false, queueArguments);
    }

    private Queue queue4() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getCanvasQueueName(), true, false, false, queueArguments);
    }

    private Queue queue5() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getCampaignQueueName(), true, false, false, queueArguments);
    }

    private Queue queue6() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getPushBrazeQueueName(), true, false, false, queueArguments);
    }

    private Queue queue7() {
        Map<String, Object> queueArguments = new HashMap<>();
        return new Queue(messageQueueProperties.getEmailBouncedStatusName(), true, false, false, queueArguments);
    }

    @Bean
    public FanoutExchange exchange() {
        return new FanoutExchange(messageQueueProperties.getPushNotificationExchangeName());
    }

    @Bean
    public Binding binding(Queue queue, FanoutExchange exchange) {
        return BindingBuilder.bind(queue).to(exchange);
    }


    private AmqpAdmin getAmqpAdmin(ConnectionFactory connectionFactory){
        AmqpAdmin amqpAdmin = new RabbitAdmin(connectionFactory);
        amqpAdmin.declareQueue(queue1());
        amqpAdmin.declareQueue(queue2());
        amqpAdmin.declareQueue(queue4());
        amqpAdmin.declareQueue(queue3());
        amqpAdmin.declareQueue(queue5());
        amqpAdmin.declareQueue(queue6());
        amqpAdmin.declareQueue(queue7());

        amqpAdmin.declareExchange(exchange());
        amqpAdmin.declareBinding(binding(queue6(), exchange()));

        return amqpAdmin;
    }

    @Bean
    public Jackson2JsonMessageConverter jackson2JsonMessageConverter(ObjectMapper objectMapper) {
        objectMapper.setDefaultPropertyInclusion(
                JsonInclude.Value.construct(JsonInclude.Include.ALWAYS, JsonInclude.Include.NON_NULL));
        return new Jackson2JsonMessageConverter(objectMapper);
    }

    private RabbitTemplate buildTemplate() {
        RabbitTemplate rabbitTemplate = new RabbitTemplate(createCachingConnectionFactory(BROKER_NOTIFICATIONS));
        rabbitTemplate.setMessageConverter(jackson2JsonMessageConverter(objectMapper));
        return rabbitTemplate;
    }

    @Bean
    public RabbitTemplate eventsTemplate() {
        RabbitTemplate rabbitTemplate = buildTemplate();
        rabbitTemplate.setRoutingKey(messageQueueProperties.getCampaignQueueName());
        return buildTemplate();
    }

    @Bean
    @Primary
    public RabbitTemplate defaultRabbitTemplate() {
        return buildTemplate();
    }
}
```

**Comment by garyrussell** [comment]
>Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: No correlation header in reply
>    at org.springframework.amqp.rabbit.core.RabbitTemplate.onMessage(RabbitTemplate.java:2663) ~[spring-rabbit-2.4.5.jar:2.4.5]

This implies that you have somehow set a `RabbitTemplate` as a message listener, which is not shown in any of your configuration.

The only `setMessageListener` I see sets a `messageListenerAdapter` and the adapter wraps a `messageBrokerReceiver` (which you don't show).

So, clearly something is messed up.

Please provide an [MCRE](https://stackoverflow.com/help/minimal-reproducible-example) so we can see what you are doing wrong.

**Comment by marcosstefani** [comment]
Hi @garyrussell . Follow an functional example: https://github.com/marcosstefani/example-rabbitmq

I created one endpoint to simulate: 
```
curl --request PUT \
  --url http://localhost:8080/test/publish \
  --header 'Content-Type: application/json' \
  --data '{
	"example": "test of message"
}'
```

**Comment by garyrussell** [comment]
Looks like some subtle change in the way Boot/Spring resolves dependencies.

You have designated one of the `RabbitTemplate`s as `@Primary`. Since it implements `ChannelAwareMessageListener` this is being resolved as the bean to inject into the adapter.

Furthermore, I don't see a bean declaration for a `MessageBrokerReceiver`. However, even when I add a bean, we still get the primary template as the listener (because it is the primary `ChannelAwareMessageListener`).

Narrowing the type of the dependency resolves it...

```java
    @Bean
    public MessageListenerAdapter listenerMessageQueueAdapter(MessageBrokerReceiver messageBrokerReceiver) {
        return new MessageListenerAdapter(messageBrokerReceiver);
    }

    @Bean
    MessageBrokerReceiver messageBrokerReceiver() {
        return new MessageBrokerReceiver();
    }
```

**Comment by garyrussell** [comment]
By the way, you don't need an adapter since your listener is already a `ChannelAwareMessageListener` so it doesn't need adapting.

**Comment by marcosstefani** [comment]
If I remove the adapter I receive that message in my application startup.
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method notificationsContainer in com.marcosstefani.example.MessageQueueConfiguration required a bean of type 'org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter' in your configuration.


Process finished with exit code 1
```

**Comment by marcosstefani** [comment]
With the Adapter, when adding the Bean MessageBrokerReceiver I still get the same error when trying to receive the message.

**Comment by garyrussell** [comment]
As I said, and show above; you need to declare the `MessageBrokerReceiver` as a `@Bean` - I got the same error until I did that.

**Comment by garyrussell** [comment]
You need to remove all the references to `MessageListenerAdapter`.

**Comment by marcosstefani** [comment]
Thanks for the instructions @garyrussell . I just don't understand how well this worked well. :D thanks.
