### ISSUE TITLE
RabbitAdmin isn't able to recover all queues when 'redeclareManualDeclarations' is set

### ISSUE THREAD

**Issue by Adler95** [spring-projects/spring-amqp#2455]
**In what version(s) of Spring AMQP are you seeing this issue?**

For example:

2.4.6

**Describe the bug**

We are creating multiple anonymous queues, and each of them is bound to its own SimpleMessageListenerContainer. Because these queues are not declared as beans in the application context, we are setting the 'redeclareManualDeclarations' property to true, so all of the queues should be able to recover if the connection to the broker is lost. In this specific case, we are setting 7 queues in such a way, all of them are successfully created on startup. When connection to the broker is lost only 6 are able to recover successfully while one always fails with 3 attempts. This problem is not bound to a specific queue, because if we, for example, remove this "problematic" queue that is not able to recover, the same problem occurs with the next one. It seems that the first queue that tries to recover after the connection is lost always fails

**To Reproduce**

Create multiple anonymous queues, each of them bound to its own SimpleMessageListenerContainer, start the application and check that all queues were successfully created. Close the connection (RabbitMQ management/TCPView/...) 

Here is the exception as seen from our application:
```
2023-05-09 15:32:35.217  WARN 14496 --- [ 127.0.0.1:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occurred (Exception message: Connection reset)
2023-05-09 15:32:35.649  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@f47aec4: tags=[[amq.ctag-sHxcRB8b6HRk_y4hdCftQA]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,1), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@212559c9 [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53779], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.649  INFO 14496 --- [enerContainer-2] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2023-05-09 15:32:35.655  INFO 14496 --- [enerContainer-2] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#290ba157:1/SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792]
2023-05-09 15:32:35.670  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Failed to declare queue: xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg
2023-05-09 15:32:35.672  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Queue declaration failed; retries left=3

org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:760)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:637)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:624)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1378)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1223)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1162)
	at jdk.proxy2/jdk.proxy2.$Proxy229.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:738)
	... 5 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 14 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:517)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:341)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)
	... 1 common frames omitted

2023-05-09 15:32:35.680  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@3f35e8ce: tags=[[amq.ctag-hWAsM9AmpUSyoUhFp2yKfg]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,7), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.680  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@7457d0bd: tags=[[amq.ctag-vfIYtahYnGqBleLNebTl_w]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,4), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.696  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@726ea4bb: tags=[[amq.ctag-7Jmb0EmvRX-hpje1cZK2Xw]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,5), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.696  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@340dcc7: tags=[[amq.ctag-TbW8F84jghzLb2obJlWGpA]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,2), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.696  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@6db2d93a: tags=[[amq.ctag-vgR3WlZHdNq0UsO05A0PWw]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,6), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:35.712  INFO 14496 --- [enerContainer-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@3acdef15: tags=[[amq.ctag-mZF7HjeIuEU3UjRo-bUyHw]], channel=Cached Rabbit Channel: AMQChannel(amqp://test@127.0.0.1:5672/xx,3), conn: Proxy@1d1dbed6 Shared Rabbit Connection: SimpleConnection@54bfcdba [delegate=amqp://test@127.0.0.1:5672/xx, localPort= 53792], acknowledgeMode=AUTO local queue size=0
2023-05-09 15:32:40.676  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Failed to declare queue: xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg
2023-05-09 15:32:40.676  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Queue declaration failed; retries left=2

org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:760)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:637)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:624)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1378)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1223)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1162)
	at jdk.proxy2/jdk.proxy2.$Proxy229.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:738)
	... 5 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 14 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:517)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:341)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)
	... 1 common frames omitted

2023-05-09 15:32:45.689  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Failed to declare queue: xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg
2023-05-09 15:32:45.689  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Queue declaration failed; retries left=1

org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:760)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:637)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:624)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1378)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1223)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1162)
	at jdk.proxy2/jdk.proxy2.$Proxy229.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:738)
	... 5 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 14 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:517)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:341)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)
	... 1 common frames omitted

2023-05-09 15:32:50.698  WARN 14496 --- [enerContainer-2] o.s.a.r.listener.BlockingQueueConsumer   : Failed to declare queue: xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg
2023-05-09 15:32:50.698 ERROR 14496 --- [enerContainer-2] o.s.a.r.l.SimpleMessageListenerContainer : Consumer threw missing queues exception, fatal=true

org.springframework.amqp.rabbit.listener.QueuesNotAvailableException: Cannot prepare queue for listener. Either the queue doesn't exist or the broker will not allow us to use it.
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.handleDeclarationException(BlockingQueueConsumer.java:710)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:644)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:624)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1378)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1223)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:760)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.passiveDeclarations(BlockingQueueConsumer.java:637)
	... 4 common frames omitted
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:1012)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1162)
	at jdk.proxy2/jdk.proxy2.$Proxy229.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:738)
	... 5 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 13 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'xxxx.xxxx.50wnVVcNTfSidLxo_M8jZg' in vhost 'xx', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:517)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:341)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)
	... 1 common frames omitted

2023-05-09 15:32:50.699 ERROR 14496 --- [enerContainer-2] o.s.a.r.l.SimpleMessageListenerContainer : Stopping container from aborted consumer
2023-05-09 15:32:50.700  INFO 14496 --- [enerContainer-2] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2023-05-09 15:32:50.700  INFO 14496 --- [enerContainer-2] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
```

**Expected behavior**

All queues should be able to recover if connections is lost

**Comment by artembilan** [comment]
Wasn't this fixed in the: https://github.com/spring-projects/spring-amqp/issues/2452 ?

**Comment by garyrussell** [comment]
Fixed in 2.4.13 https://github.com/spring-projects/spring-amqp/issues/2454

Not currently scheduled, because it's the only patch and there is an easy work around.

Just add a dummy `Queue` bean with `shouldDeclare=false`.

**Comment by garyrussell** [comment]
Please show exactly how you are defining and declaring your queues. Auto-delete queues MUST be declared with `x-queue-master-locator` set to `client-local`; this happens automatically if you use `AnonymousQueue` (since 2.2).

However, if a different connection is used for that listener (as indicated by the different local port), then something else is going on - it must be using a different connection factory. If there is not an admin that uses that factory then no declaration can happen.

Please provide much more information, logs, etc., including `Created new connection: ... 53792...`.

**Comment by gkirill** [comment]
For whoever is going to use `redeclareManualDeclarations=true`, just don't forget to call `afterPropertiesSet()` on `RabbitAdmin` after `setRedeclareManualDeclarations(true)`.
