### ISSUE TITLE
Not support binding a queue to a custom Exchange whth Annotation

### ISSUE THREAD

**Issue by hyhy01** [spring-projects/spring-amqp#598]
When binding a queue to the rabbitmq_lvc  exchange,
```
@RabbitListener(
            bindings = @QueueBinding(
                    value = @Queue(),
                    exchange = @Exchange(
                            value = "lvc",
                            type = "'x-lvc'",//ExchangeTypes.TOPIC,
                            durable = "true"
                    ),
                    key="test"
            )
    )
```
An exception will be thrown.
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myBean' defined in file [D:\git\gs-messaging-rabbitmq\complete\target\classes\hello\MyBean.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Unexpected exchange type: 'x-lvc'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	.................................
Caused by: org.springframework.beans.factory.BeanInitializationException: Unexpected exchange type: 'x-lvc'
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.declareExchangeAndBinding(RabbitListenerAnnotationBeanPostProcessor.java:598) ~[spring-rabbit-1.7.1.RELEASE.jar:na]
```

[RabbitListenerAnnotationBeanPostProcessor.java](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java#L595)

**Comment by panchenko** [comment]
@hyhy01 have you tried without the single quotes?

**Comment by hyhy01** [comment]
@panchenko yes

**Comment by panchenko** [comment]
My question here was not too smart :-)
