### ISSUE TITLE
Unknown channel number

### ISSUE THREAD

**Issue by Genitana** [spring-projects/spring-amqp#627]
I use rabbitmq as a message queue ，and i use Spring amqp which is a easy way to  send and receive messages. but i meet this problem when i send message to fanout exchange : 
  
`2017-06-29 07:37:50.840 ERROR 1 --- [o-1234-exec-153] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.amqp.AmqpIOException: java.io.IOException] with root cause`
`com.rabbitmq.client.impl.UnknownChannelException: Unknown channel number 75`
  `at com.rabbitmq.client.impl.ChannelManager.getChannel(ChannelManager.java:80) ~[amqp-client-3.5.7.jar!/:na]`
 `at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:554) ~[amqp-client-3.5.7.jar!/:na]`
`at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]`
This is when I use loadrunner test 50 concurrent problems will appear ，i build  5  fanout exchange，and every   fanout exchange  binds 10 queues ,each time a  message is sent to a random  exchange  .When 10 concurrent time will also be the problem , but  after a minute later . I used a total of two computer tests, one installed rabbimq, another send message.
i use  this  send message : 
` rabbitTemplate.convertAndSend(deptid, deptid, message);`

 This problem bothers me for a long time, and any help is very grateful.

**Comment by garyrussell** [comment]
Try increasing the `channelCacheSize` on the `CachingConnectionFactory`. It defaults to 25 but should be large enough to handle the number of concurrent send operations you expect.

**Comment by Genitana** [comment]
i set    
spring:
  rabbitmq:
    channelCacheSize: 2000    ；
the  error appear again

**Comment by Genitana** [comment]
i  upgraded the version to 1.4.5 
 `  springBootVersion = '1.4.5.RELEASE'`       
`  springCloudVersion = 'Camden.SR7' `   
        `  spring-rabbit-1.6.8.RELEASE.jar`   

the error did not appear  again. 
 when I send a message to a fanout exchange,
   1，get a channel 
  2 ,  send message to  fanout exchange
3,  fanout exchange  Send the message to the queue which bind to it
4, close  channel 

i have  some questions : 

question 1: Is this step right? 
question 2: the step 3  ，is rabbitmq server doing this or rabbitmq client doing this thing？
question 3: what is the whole life cycle of the channel ?

Very much looking forward to your answer

**Comment by garyrussell** [comment]
1. Yes, but you might find it easier to just let the `RabbitTemplate` manage the channel for you.

    template.convertAndSend("fanout", "", "foo")

or 

    template.send("fanout", "", message);

The template will reliably close the channel (on success or failure).

2. The server does the routing; the publishing client does not know what is bound to the exchange.

3. If there is a channel in the cache, then `connection.createChannel(...)`  gets one from the cache, otherwise it creates on. When a channel is `close()`d, if there is room in the cache (`channelCacheSize`) the channel is put into the cache instead of being closed. If the cache is full, the channel is actually closed.

**Comment by Genitana** [comment]
@garyrussell 
     Thank you very much for your answer, I have some more understanding of this，i am using RabbitTemplate to send the message now，It is really easier  .  
     I now have 10  fanout exchanges , each exchanges binds 10 queues , as you know , a fanout exchange routes messages to all of the queues that are bound to it and the routing key is ignored. it   worked  very well in low concurrency ，but in the high concurrency(50  concurrent)of the situation was  very bad .There was no error  in the log , but the number of publish which i saw from the rabbitmq management page was  smaller than 50  .This is not normal . This number should be large , at least it should be hundreds  . So what's the problem  ? If  i want use fanout exchange in  high concurrency ,  is there any good way to solve it  ?
 Looking forward to your reply

**Comment by garyrussell** [comment]
I have not seen such problems as long as the channel cache size is large enough. If you can post a sample application that exhibits the behavior, I can take a look.

**Comment by Genitana** [comment]
@garyrussell 
Thank you very much ， but i would like to try it myself   , if i can't fix it , i will come for your help .  i  I send a message to a fanout exchange which bound 10 queues , the response time is 36 mm  ,  is  the response be returned when the message arrives at the queue  or   the rabbitmq server exchange  received a message ?

**Comment by artembilan** [comment]
Depends of your `mandatory` and `immediate` options: https://stackoverflow.com/questions/6386117/rabbitmq-use-of-immediate-and-mandatory-bits

**Comment by garyrussell** [comment]
Closing due to lack of activity; please reopen if you still feel there is an issue.
