### ISSUE TITLE
auto delete exchange disappears after creation

### ISSUE THREAD

**Issue by lrozek** [spring-projects/spring-amqp#628]
hello,

I have a following problem. During listener recovery (after connection to RabbiMQ is restored) `RabbitAdmin` recreates exchanges, queues and bindings. According to logs, exchange and queues are created successfully, however it fails when `RabbitAdmin` tries to bind first queue to that exchange. The reason for the failure was missing exchange which was created during this initialization process. In RabbitMQ management web console I could see that all queues were created. The exchange was missing, and also the bindings were not there. The only situation I encounter following problems is after listener recovery due to the connection problem between app and RabbitMQ. According to RabbitMQ docs https://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.declare.auto-delete auto delete exchange is removed after all queues have finished using it. Additionally server should allow client to create queues and bind to them before it considers the exchange to be removed. The initialization process didn't take longer then 300 millisecond so I assume it's not the case. Please have a look at enclosed logs

```
2017-07-06 20:41:04.723  INFO 7645 --- [InCUContainer-9] o.s.a.r.c.CachingConnectionFactory       : Created new connection: SimpleConnection@5ea30d5c [delegate=amqp://keyservice@100.104.5.184:5672/, localPort= 59800]
2017-07-06 20:41:04.723 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Initializing declarations
2017-07-06 20:41:04.723  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable or auto-delete Exchange (hsm.in.queue.direct) durable:false, auto-delete:true. It will be deleted by the broker if it shuts down, and can be redeclared by closing and reopening the connection.
2017-07-06 20:41:04.723  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.sk.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.723  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.gk.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.rk.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.cp.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.cu.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.rp.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.is.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.gs.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.gp.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.ac.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724  INFO 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (hsm1.rs.in.queue) durable:false, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2017-07-06 20:41:04.724 TRACE 7645 --- [InCUContainer-9] o.s.a.r.c.CachingConnectionFactory       : Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,84), conn: Proxy@614ec303 Shared Rabbit Connection: SimpleConnection@5ea30d5c [delegate=amqp://keyservice@100.104.5.184:5672/, localPort= 59800] retrieved from cache
2017-07-06 20:41:04.724 TRACE 7645 --- [InCUContainer-9] o.s.a.r.s.PublisherCallbackChannelImpl   : AMQChannel(amqp://keyservice@100.104.5.184:5672/,84) is already closed
2017-07-06 20:41:04.725 DEBUG 7645 --- [InCUContainer-9] o.s.a.r.s.PublisherCallbackChannelImpl   : PendingConfirms cleared
2017-07-06 20:41:04.728 DEBUG 7645 --- [InCUContainer-9] o.s.a.r.c.CachingConnectionFactory       : Creating cached Rabbit Channel from PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1)
2017-07-06 20:41:04.728 DEBUG 7645 --- [InCUContainer-9] o.s.a.r.s.PublisherCallbackChannelImpl   : Added listener org.springframework.amqp.rabbit.core.RabbitTemplate@52671483
2017-07-06 20:41:04.728 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitTemplate      : Added pubsub channel: Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1), conn: Proxy@614ec303 Shared Rabbit Connection: SimpleConnection@5ea30d5c [delegate=amqp://keyservice@100.104.5.184:5672/, localPort= 59800] to map, size now 1
2017-07-06 20:41:04.728 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitTemplate      : Executing callback on RabbitMQ Channel: Cached Rabbit Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1), conn: Proxy@614ec303 Shared Rabbit Connection: SimpleConnection@5ea30d5c [delegate=amqp://keyservice@100.104.5.184:5672/, localPort= 59800]
2017-07-06 20:41:04.728 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Exchange 'hsm.in.queue.direct'
2017-07-06 20:41:04.730 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.sk.in.queue.dlx'
2017-07-06 20:41:04.731 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.731 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gk.in.queue.dlx'
2017-07-06 20:41:04.732 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.732 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rk.in.queue.dlx'
2017-07-06 20:41:04.734 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.734 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.cp.in.queue.dlx'
2017-07-06 20:41:04.735 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.735 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.cu.in.queue.dlx'
2017-07-06 20:41:04.736 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.736 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rp.in.queue.dlx'
2017-07-06 20:41:04.737 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.737 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.is.in.queue.dlx'
2017-07-06 20:41:04.739 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.739 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gs.in.queue.dlx'
2017-07-06 20:41:04.740 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.740 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gp.in.queue.dlx'
2017-07-06 20:41:04.741 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.741 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.ac.in.queue.dlx'
2017-07-06 20:41:04.742 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.742 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rs.in.queue.dlx'
2017-07-06 20:41:04.743 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.743 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.sk.in.queue'
2017-07-06 20:41:04.746 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.746 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gk.in.queue'
2017-07-06 20:41:04.748 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.748 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rk.in.queue'
2017-07-06 20:41:04.756 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.757 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.cp.in.queue'
2017-07-06 20:41:04.760 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.760 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.cu.in.queue'
2017-07-06 20:41:04.768 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.768 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rp.in.queue'
2017-07-06 20:41:04.771 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.771 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.is.in.queue'
2017-07-06 20:41:04.774 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.774 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gs.in.queue'
2017-07-06 20:41:04.777 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.777 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.gp.in.queue'
2017-07-06 20:41:04.780 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.780 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.ac.in.queue'
2017-07-06 20:41:04.783 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.783 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'hsm1.rs.in.queue'
2017-07-06 20:41:04.790 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Queue with name that starts with 'amq.' cannot be declared.
2017-07-06 20:41:04.790 DEBUG 7645 --- [InCUContainer-9] o.s.amqp.rabbit.core.RabbitAdmin         : Binding destination [hsm1.sk.in.queue (QUEUE)] to exchange [hsm.in.queue.direct] with routing key [1.sk]
2017-07-06 20:41:04.833 DEBUG 7645 --- [.104.5.184:5672] o.s.amqp.rabbit.core.RabbitTemplate      : Removed pubsub channel: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1) from map, size now 0
2017-07-06 20:41:04.833 DEBUG 7645 --- [.104.5.184:5672] o.s.a.r.s.PublisherCallbackChannelImpl   : PendingConfirms cleared
2017-07-06 20:41:04.833 ERROR 7645 --- [.104.5.184:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'hsm.in.queue.direct' in vhost '/', class-id=50, method-id=20)
2017-07-06 20:41:04.834 DEBUG 7645 --- [InCUContainer-9] o.s.a.r.c.CachingConnectionFactory       : Detected closed channel on exception.  Re-initializing: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1)
2017-07-06 20:41:04.837 TRACE 7645 --- [InCUContainer-9] o.s.a.r.c.CachingConnectionFactory       : Returning cached Channel: PublisherCallbackChannelImpl: AMQChannel(amqp://keyservice@100.104.5.184:5672/,1)
2017-07-06 20:41:04.837 DEBUG 7645 --- [InCUContainer-9] o.s.a.r.l.SimpleMessageListenerContainer : Recovering consumer in 5000 ms.
2017-07-06 20:41:09.841  WARN 7645 --- [InCUContainer-9] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it
org.springframework.amqp.AmqpIOException: java.io.IOException
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71)
	at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:113)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1462)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1412)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1388)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.initialize(RabbitAdmin.java:500)
	at org.springframework.amqp.rabbit.core.RabbitAdmin$11.onCreate(RabbitAdmin.java:419)
	at org.springframework.amqp.rabbit.connection.CompositeConnectionListener.onCreate(CompositeConnectionListener.java:33)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:553)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:90)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:140)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:76)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:496)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1331)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:123)
	at com.rabbitmq.client.impl.ChannelN.queueBind(ChannelN.java:944)
	at com.rabbitmq.client.impl.ChannelN.queueBind(ChannelN.java:60)
	at org.springframework.amqp.rabbit.support.PublisherCallbackChannelImpl.queueBind(PublisherCallbackChannelImpl.java:383)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:917)
	at com.sun.proxy.$Proxy64.queueBind(Unknown Source)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.declareBindings(RabbitAdmin.java:613)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.access$300(RabbitAdmin.java:66)
	at org.springframework.amqp.rabbit.core.RabbitAdmin$12.doInRabbit(RabbitAdmin.java:505)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1456)
	... 12 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'hsm.in.queue.direct' in vhost '/', class-id=50, method-id=20)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:360)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:225)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117)
	... 25 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'hsm.in.queue.direct' in vhost '/', class-id=50, method-id=20)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:483)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:320)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:143)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:90)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:559)
	... 1 common frames omitted
2017-07-06 20:41:09.842  INFO 7645 --- [InCUContainer-9] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
```

Can you please guide me how to trace and resolve the issue. Thank you

**Comment by artembilan** [comment]
@lrozek ,

would you mind to share some simple Spring Boot app to play from our side?

Thanks, but I somehow can't compile yet how is that possible.

**Comment by garyrussell** [comment]
Discrete `Exchange` beans are always declared before queues and bindings [code here](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java#L479).

However, I see that `@Bean`s of type `Collection<Declarable>` might be declared in the wrong order, since we don't sort beans of type `Collection` [code here](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitAdmin.java#L437).

If you are using that feature [as documented here](http://docs.spring.io/spring-amqp/reference/html/_reference.html#collection-declaration), try using discrete `@Bean`s instead, as a work around.

**Comment by garyrussell** [comment]
Forget my previous (deleted) comment; we do indeed declare the collections in order.

👍  for @artembilan 's suggestion.

**Comment by lrozek** [comment]
@artembilan

That won't be so easy. It's not reproducible, or I haven't figured it out how to reproduce it yet, so I don't know how to prepare project to simulate it. It happens from time to time, once a month or even less frequently. It only occurs in one module where we use auto delete exchanges / queues. Prior to this error there is always a connectivity issue.

**Comment by garyrussell** [comment]
Closing due to inactivity.
