### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by minchina** [spring-projects/spring-amqp#643]
Hi Guys,

I build a jar by myself and i am sure i am do nothing, just run the gradle build and gradle install command,
then i get the new jar file, but when i use the jar file in my app, i get an error like below:

`Caused by: java.lang.NoClassDefFoundError: org/springframework/amqp/support/converter/SmartMessageConverter
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:489)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.buildPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:431)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:397)
	... 72 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.amqp.support.converter.SmartMessageConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 79 common frames omitted

`

could you please help me look at this?

**Comment by artembilan** [comment]
Doesn't sound like a problem in the Framework.

Please, consider to move it into some community forum, like [StackOverflow](https://stackoverflow.com/).

We don't handle questions here on GitHub.

**Comment by minchina** [comment]
ok, thanks for your help.

**Comment by artembilan** [comment]
You are always welcome here with bugs and features requests!

Everything rest not related to the Framework problems should be managed through the community forums.
