### ISSUE TITLE
ConsumerCancelledException when using Anonymous queues

### ISSUE THREAD

**Issue by whitfin** [spring-projects/spring-amqp#708]
Hi there! 

I've search all over for similar issues, and whilst there are a lot it doesn't appear that there has been an "official" solution. As such, I apologise if this is not a library issue, but it's typically good to get something on record.

Simple enough issue; I am currently writing a listener for what is effectively an anonymous queue:

```java
new Queue(someMethodToGenerateAName(), false, true, true);
```

I'm using an instance of `RabbitAdmin` to declare that queue, before then using a `SimpleMessageListenerContainer` to listen on it. Not that I think it matters, but this is all based around using https://github.com/rabbitmq/rabbitmq-management-exchange.

```java
// base queue that will have messages received on it, as a replyTo
Queue responseQueue = new Queue(someMethodToGenerateAName(), false, true, true);

// "factory" here is a CachingConnectionFactory
RabbitAdmin rabbitAdmin = new RabbitAdmin(factory);
rabbitAdmin.declareQueue(responseQueue);

// not used in this block, but this is the template used for publish
RabbitTemplate rabbitTemplate = new RabbitTemplate(factory);

SimpleMessageListenerContainer listenerContainer = new SimpleMessageListenerContainer(factory);

listenerContainer.setMessageListener(message -> {
    // do whatever
});

listenerContainer.setQueues(responseQueue);
listenerContainer.start();
```

All of this works great, just as expected *for a single message*. I publish one message to the exchange, and it comes back to my listener and everything is fine. However the moment I publish a second message, I get a bunch of this:

```java
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '8827e82dd3b24ecc' in vhost 'project', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
	... 12 common frames omitted
```

Either there's some weird configuration I'm missing here, or something is wrong - the fact it works for the first message makes me think that it might be something internal that I'm not understanding properly. 

Here is everything relevant I can find in the debug logging:

```java
[2018-02-06T16:17:08.621Z] [o.s.a.r.c.CachingConnectionFactory] [INFO] Attempting to connect to: localhost:5672
[2018-02-06T16:17:08.700Z] [o.s.a.r.c.CachingConnectionFactory] [INFO] Created new connection: SpringAMQP#43c7fe8a:0/SimpleConnection@3009eed7 [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62486]
[2018-02-06T16:17:08.703Z] [o.s.a.r.c.CachingConnectionFactory] [INFO] Attempting to connect to: localhost:5672
[2018-02-06T16:17:08.709Z] [o.s.a.r.c.CachingConnectionFactory] [INFO] Created new connection: SpringAMQP#48e41b5d:0/SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:08.826Z] [o.s.a.r.c.CachingConnectionFactory] [DEBUG] Creating cached Rabbit Channel from AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1)
[2018-02-06T16:17:08.843Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Executing callback RabbitAdmin$$Lambda$45/992054388 on RabbitMQ Channel: Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:08.843Z] [o.s.a.r.c.RabbitAdmin] [DEBUG] declaring Queue '8827e82dd3b24ecc'
[2018-02-06T16:17:08.850Z] [o.s.a.r.l.SimpleMessageListenerContainer] [DEBUG] Starting Rabbit listener container.
[2018-02-06T16:17:08.856Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Starting consumer Consumer@7e0f9528: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:08.870Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Started on queue '8827e82dd3b24ecc' with tag amq.ctag-wzsrlkIoHh4fiBrzTxYqhA: Consumer@7e0f9528: tags=[{amq.ctag-wzsrlkIoHh4fiBrzTxYqhA=8827e82dd3b24ecc}], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487], acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:08.870Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] ConsumeOK : Consumer@7e0f9528: tags=[{amq.ctag-wzsrlkIoHh4fiBrzTxYqhA=8827e82dd3b24ecc}], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487], acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:08.908Z] [o.m.d.connection] [INFO] Opened connection [connectionId{localValue:3, serverValue:87}] to localhost:27017
[2018-02-06T16:17:11.170Z] [o.s.a.r.c.CachingConnectionFactory] [DEBUG] Creating cached Rabbit Channel from AMQChannel(amqp://rabbit@127.0.0.1:5672/project,2)
[2018-02-06T16:17:11.170Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Executing callback RabbitTemplate$$Lambda$56/332564935 on RabbitMQ Channel: Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,2), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:11.170Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Publishing message (Body:'[B@53bb71e5(byte[0])' MessageProperties [headers={}, type=GET, correlationId=0d03f6c1e02c6298, replyTo=8827e82dd3b24ecc, contentType=application/octet-stream, contentLength=0, deliveryMode=PERSISTENT, priority=0, deliveryTag=0])on exchange [project.admin], routingKey = [/queues/project]
[2018-02-06T16:17:11.181Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Storing delivery for Consumer@7e0f9528: tags=[{amq.ctag-wzsrlkIoHh4fiBrzTxYqhA=8827e82dd3b24ecc}], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487], acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:11.182Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Received message: (Body:'[{"node":"rabbit@e866abe0debd","arguments":{},"exclusive":true,"auto_delete":true,"durable":false,"vhost":"project","name":"8827e82dd3b24ecc"}]' MessageProperties [headers={}, type=200, correlationId=0d03f6c1e02c6298, contentType=application/json, contentLength=0, redelivered=false, receivedExchange=, receivedRoutingKey=8827e82dd3b24ecc, deliveryTag=1, consumerTag=amq.ctag-wzsrlkIoHh4fiBrzTxYqhA, consumerQueue=8827e82dd3b24ecc])
[2018-02-06T16:17:12.927Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Executing callback RabbitAdmin$$Lambda$62/1805031342 on RabbitMQ Channel: Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,2), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:13.826Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Executing callback RabbitTemplate$$Lambda$56/332564935 on RabbitMQ Channel: Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,2), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:13.826Z] [o.s.a.r.c.RabbitTemplate] [DEBUG] Publishing message (Body:'[B@53bb71e5(byte[0])' MessageProperties [headers={}, type=GET, correlationId=fbe0a25b6a2097db, replyTo=8827e82dd3b24ecc, contentType=application/octet-stream, contentLength=0, deliveryMode=PERSISTENT, priority=0, deliveryTag=0])on exchange [project.admin], routingKey = [/queues/project]
[2018-02-06T16:17:13.826Z] [o.s.a.r.l.BlockingQueueConsumer] [WARN] Cancel received for amq.ctag-wzsrlkIoHh4fiBrzTxYqhA (8827e82dd3b24ecc); Consumer@7e0f9528: tags=[{amq.ctag-wzsrlkIoHh4fiBrzTxYqhA=8827e82dd3b24ecc}], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487], acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:13.922Z] [o.s.a.r.l.SimpleMessageListenerContainer] [DEBUG] Consumer raised exception, processing can restart if the connection factory supports it
org.springframework.amqp.rabbit.support.ConsumerCancelledException: null
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.nextMessage(BlockingQueueConsumer.java:500)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:780)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:769)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1010)
	at java.lang.Thread.run(Thread.java:748)
[2018-02-06T16:17:13.923Z] [o.s.a.r.l.SimpleMessageListenerContainer] [INFO] Restarting Consumer@7e0f9528: tags=[{}], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487], acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:13.923Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Closing Rabbit Channel: Cached Rabbit Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1), conn: Proxy@27898e13 Shared Rabbit Connection: SimpleConnection@5333f08f [delegate=amqp://rabbit@127.0.0.1:5672/project, localPort= 62487]
[2018-02-06T16:17:13.923Z] [o.s.a.r.c.CachingConnectionFactory] [DEBUG] Closing cached Channel: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,1)
[2018-02-06T16:17:13.927Z] [o.s.a.r.l.BlockingQueueConsumer] [DEBUG] Starting consumer Consumer@1f19b529: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
[2018-02-06T16:17:13.930Z] [o.s.a.r.c.CachingConnectionFactory] [DEBUG] Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '8827e82dd3b24ecc' in vhost 'project', class-id=50, method-id=10)
[2018-02-06T16:17:13.930Z] [o.s.a.r.c.CachingConnectionFactory] [DEBUG] Detected closed channel on exception.  Re-initializing: AMQChannel(amqp://rabbit@127.0.0.1:5672/project,2)
[2018-02-06T16:17:13.932Z] [o.s.a.r.l.BlockingQueueConsumer] [WARN] Failed to declare queue: 8827e82dd3b24ecc
[2018-02-06T16:17:13.932Z] [o.s.a.r.l.BlockingQueueConsumer] [WARN] Queue declaration failed; retries left=3
org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[8827e82dd3b24ecc]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:711)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:587)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:964)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:144)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:991)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:981)
	at com.sun.proxy.$Proxy42.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:690)
	... 3 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '8827e82dd3b24ecc' in vhost 'project', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:288)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
	... 12 common frames omitted
```

Based on the logs, it looks like something just explodes on the second message (and it's always the second message). This is 100% consistent in my project (which I sadly cannot share fully, only relevant snippets), so clarification on whether this is configuration annoyances, some effect of how I'm using my templates, or just a bug would be appreciated.

Let me know if you need anything else trying; I tried to include as much as possible, but if I can grab anything more useful, just drop a note.

*Edit:* I should also note that the message being published is the exact same for the 1st and 2nd message sent, so it's not variation of the payloads.

**Comment by artembilan** [comment]
Works well for me:
````java
@Test
public void testGh708() throws Exception {

	Queue responseQueue = new Queue(UUID.randomUUID().toString(), false, true, true);

	CachingConnectionFactory factory = new CachingConnectionFactory("localhost");
	RabbitAdmin rabbitAdmin = new RabbitAdmin(factory);
	rabbitAdmin.declareQueue(responseQueue);


	RabbitTemplate rabbitTemplate = new RabbitTemplate(factory);
	rabbitTemplate.setRoutingKey(responseQueue.getName());

	SimpleMessageListenerContainer listenerContainer = new SimpleMessageListenerContainer(factory);

	CountDownLatch messagesLatch = new CountDownLatch(3);

	listenerContainer.setMessageListener(message -> {
		System.out.println(message);
		messagesLatch.countDown();
	});

	listenerContainer.setQueues(responseQueue);
	listenerContainer.start();

	rabbitTemplate.convertAndSend("foo");
	rabbitTemplate.convertAndSend("bar");
	rabbitTemplate.convertAndSend("baz");

	assertTrue(messagesLatch.await(10, TimeUnit.SECONDS));
}
````

And I have logs like this:
```
2018-02-07 17:30:30,509  INFO org.springframework.amqp.rabbit.connection.CachingConnectionFactory [main] : Attempting to connect to: localhost:5672
2018-02-07 17:30:30,513  INFO org.springframework.amqp.rabbit.connection.CachingConnectionFactory [main] : Created new connection: SpringAMQP#41c07648:0/SimpleConnection@781e7326 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 57854]
(Body:'foo' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=, receivedRoutingKey=220f97db-c26a-49e7-9f95-10a1f0ff3a01, deliveryTag=1, consumerTag=amq.ctag-oxE5rUdzdpOSGjwwkuvxTw, consumerQueue=220f97db-c26a-49e7-9f95-10a1f0ff3a01])
(Body:'bar' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=, receivedRoutingKey=220f97db-c26a-49e7-9f95-10a1f0ff3a01, deliveryTag=2, consumerTag=amq.ctag-oxE5rUdzdpOSGjwwkuvxTw, consumerQueue=220f97db-c26a-49e7-9f95-10a1f0ff3a01])
(Body:'baz' MessageProperties [headers={}, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=, receivedRoutingKey=220f97db-c26a-49e7-9f95-10a1f0ff3a01, deliveryTag=3, consumerTag=amq.ctag-oxE5rUdzdpOSGjwwkuvxTw, consumerQueue=220f97db-c26a-49e7-9f95-10a1f0ff3a01])
2018-02-07 17:30:30,750  INFO org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer [main] : Waiting for workers to finish.
2018-02-07 17:30:31,743  INFO org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer [main] : Successfully waited for workers to finish.
```

**Comment by whitfin** [comment]
@artembilan it appears this is no longer occurring - I'll reopen if it happens again :)
