### ISSUE TITLE
JDK-8145964 : NoClassDefFound error in transforming lambdas

### ISSUE THREAD

**Issue by lancedfr** [spring-projects/spring-amqp#836]
https://github.com/spring-projects/spring-amqp/blob/0dca5bcdedafa680e7fe654cfa97591ac23b3f8f/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L117

There is a [JDK bug](https://bugs.java.com/view_bug.do?bug_id=JDK-8145964) being triggered on the above line. I'm running Java 1.8.0u171 and spring-rabbit 2.0.4.RELEASE. The JDK bug was only fixed in JDK 9 as seen in the JDK bug report.

I've managed to fix the issue by providing my own listener container which does not assign member variables using "this" key word lamda expressions.

```
2018-10-25 16:55:36.807 ERROR [audit-event-service,,,] 1 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer thread error, thread abort.

java.lang.NoClassDefFoundError: org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer$$Lambda$782
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$$Lambda$782/826490361.invokeListener(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at brave.spring.rabbit.TracingRabbitListenerAdvice.invoke(TracingRabbitListenerAdvice.java:84)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at org.springframework.amqp.rabbit.listener.$Proxy180.invokeListener(Unknown Source)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$$Lambda$782
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 common frames omitted

2018-10-25 16:55:36.826 ERROR [audit-event-service,,,] 1 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Stopping container from aborted consumer
2018-10-25 16:55:36.826  INFO [audit-event-service,,,] 1 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2018-10-25 16:55:36.826  INFO [audit-event-service,,,] 1 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
```

**Comment by garyrussell** [comment]
@lancedfr Thanks. 

Can you provide some information (or a test case) for how to reproduce it?

**Comment by artembilan** [comment]
@lancedfr ,

gentle ping.
Any possible way how to reproduce?

Thanks

**Comment by lancedfr** [comment]
hi all, apologies for the delay.. @panchenko is correct.. when starting application with ```java -javaagent:``` our work around is clean and this issue is defiantly not a show stopper.. this will enable our team to upgrade to java 9 sooner than later.

I'm happy that its not a spring-amqp issue and this issue be closed.
