### ISSUE TITLE
 Listener not registered exception from RabbitTemplate.sendAndReceive

### ISSUE THREAD

**Issue by ssinger** [spring-projects/spring-amqp#846]
I have code that is as follows

~~~      
            Message reply = template.sendAndReceive(exchange, routingKey,
                message);
~~~

where template is a RabbitTemplate instance.

This sometimes throws the following exception.

~~~
Caused by: java.lang.IllegalArgumentException: Listener not registered: org.springframework.amqp.rabbit.core.RabbitTemplate@4525951e []
        at org.springframework.util.Assert.notNull(Assert.java:193) ~[spring-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.amqp.rabbit.support.PublisherCallbackChannelImpl.addPendingConfirm(PublisherCallbackChannelImpl.java:944) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
   at com.sun.proxy.$Proxy116.addPendingConfirm(Unknown Source) ~[?:?]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.setupConfirm(RabbitTemplate.java:2026) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doSend(RabbitTemplate.java:1998) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.exchangeMessages(RabbitTemplate.java:1751) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doSendAndReceiveAsListener(RabbitTemplate.java:1702) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doSendAndReceiveWithDirect(RabbitTemplate.java:1664) ~[spring-rabbit-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        ... 108 more
~~~

Our RabbitTemplate Bean is created as follows

~~~
@Bean
public RabbitTemplate rabbitTemplate() {
        RabbitTemplate template = new RabbitTemplate();
        template.setConnectionFactory(connectionFactory);
        template.setReplyTimeout(replyTimeoutMs);
        ExponentialBackOffPolicy backOffPolicy = new ExponentialBackOffPolicy();
        backOffPolicy.setInitialInterval(500);
        backOffPolicy.setMultiplier(10.0);
        backOffPolicy.setMaxInterval(10000);
        RetryTemplate retryTemplate = new RetryTemplate();
        retryTemplate.setBackOffPolicy(backOffPolicy);
        template.setRetryTemplate(retryTemplate);
        template.setConfirmCallback(publisherConfirmCorrelator);
        return template;
    }
~~~

From what I can tell we sometimes get this error and we sometimes don't (the sendAndReceive works). I haven't yet figured out what is causing this to work/not work.

We recently upgraded from spring boot 1.3.8 to spring-boot 2.0.5 (spring-amqp 2.0.6).
We never noticed this before the upgrade.

What could cause this type of exception?

**Comment by garyrussell** [comment]
The only way I can see that happening is if the connection factory does not have confirms (or returns) enabled.

Although I can see there is a possibility that the channel was closed by some external condition just before the template is registering the pending confirmation before sending the message.

If you can reproduce it with DEBUG logging enabled, it would help.

**Comment by ssinger** [comment]
This is the relevant DEBUG output with some internal details removed.
After this snippet the exception handlers have been invoked.
I don't see any indication in the logs that there is a connection error at this point. It is possible that there was a connection error much earlier.

~~~
2018-11-13 09:37:09,745 DEBUG o.s.a.r.c.CachingConnectionFactory [https-jsse-nio-10.10.10.10-8090-exec-13] Creating cached Rabbit Channel from PublisherCallbackChannelImpl: AMQChannel(am
qp://acemq@10.10.10.10:5601/mymq,14)
2018-11-13 09:37:09,750 DEBUG o.s.a.r.l.DirectMessageListenerContainer$SimpleConsumer [pool-2-thread-6] New SimpleConsumer [queue=amq.rabbitmq.reply-to, consumerTag=amq.ctag-Z43efUvOsCwW
tnr_kSzIZw identity=7802cd23] consumeOk
2018-11-13 09:37:09,750 DEBUG o.s.a.r.c.RabbitTemplate [https-jsse-nio-10.10.10.10-8090-exec-13] Sending message with tag 6628
2018-11-13 09:37:09,750 DEBUG o.s.a.r.c.RabbitTemplate [https-jsse-nio-10.10.10.10-8090-exec-13] Publishing message (Body:'[B@ceb96d5(byte[59])' MessageProperties [headers={...},correlationId=6628, replyTo=amq.rabbitmq.reply-to, contentType=application/octet-stream,contentLength=0, deliveryMode=PERSISTENT, priority=0, deliveryTag=0])on exchange [....], routingKey = [myroutingkey]
2018-11-13 09:37:09,775 DEBUG o.s.b.f.s.AbstractBeanFactory [https-jsse-nio-10.10.10.10-8090-exec-13] Returning cached instance of singleton bean 'globalController'
~~~

The connection factory is a caching factory with returns enabled

~~~
   @Bean
    public ConnectionFactory connectionFactory() {
        CachingConnectionFactory connectionFactory = new CachingConnectionFactory(
            host, port);
        connectionFactory.setUsername(username);
        connectionFactory.setPassword(password);
        connectionFactory.setVirtualHost(virtualHost);
        connectionFactory.setPublisherConfirms(true);
        return connectionFactory;
    }
~~~

**Comment by garyrussell** [comment]
It's a bug with the new `DirectReplyToContainer` mechanism for handling replies.

Set `template.setUseDirectReplyToContainer(false);` as a work around (reverts to the previous mechanism).
