### ISSUE TITLE
AbstractRabbitListenerContainerFactory throws NullPointerException after upgrade to 2.1.2.RELEASE

### ISSUE THREAD

**Issue by Maarten-Damen** [spring-projects/spring-amqp#866]
After upgrading to spring-boot 2.1.1 we got a NullPointerException when both Hibernate and RabbitAutoConfiguration are initializing. It seems to be a corner case which makes it hard to reproduce on a small test project that makes sense, but the stacktrace ends with:
`Caused by: java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.config.AbstractRabbitListenerContainerFactory.getAdviceChain(AbstractRabbitListenerContainerFactory.java:198)
	at brave.spring.rabbit.SpringRabbitTracing.decorateSimpleRabbitListenerContainerFactory(SpringRabbitTracing.java:170)
	at org.springframework.cloud.sleuth.instrument.messaging.SleuthRabbitBeanPostProcessor.postProcessBeforeInitialization(TraceMessagingAutoConfiguration.java:186)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	... 41 common frames omitted`

After checking the changes in AbstractRabbitListenerContainerFactory it seems to be related to changes done in this commit https://github.com/spring-projects/spring-amqp/commit/2ef76b4bb2aa1b174894ae1845edf305deaa3052#diff-26d26e39a825e80840186d082e3c1eaa. The JavaDoc of getAdviceChain looks like it would be possible to have the adviceChain being null, but by adding the Arrays.copyOf as done in this commit will cause NullPointerExceptions when it is actually null.

**Comment by garyrussell** [comment]
Thanks for reportingl - already fixed on master : https://jira.spring.io/browse/AMQP-846
