### ISSUE TITLE
The ApplicationContext is closed and the ConnectionFactory can no longer create connections

### ISSUE THREAD

**Issue by davidarce** [spring-projects/spring-amqp#890]
**Affects Version(s):** 2.0.8.RELEASE

## How does spring amqp shutting down work on spring boot?

When executing the gracefull shutting down of the spring boot Amqp throws the exception of AmqpApplicationContextClosedException in SimpleMessageListenerContainer.doShutdown it seems that when doing the shutdown the context of spring no longer exists

```
org.springframework.amqp.AmqpApplicationContextClosedException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:622) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:578) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$600(CachingConnectionFactory.java:99) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1053) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at com.sun.proxy.$Proxy166.basicCancel(Unknown Source) ~[na:na]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.basicCancel(BlockingQueueConsumer.java:399) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doShutdown(SimpleMessageListenerContainer.java:521) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.shutdown(AbstractMessageListenerContainer.java:1100) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doStop(AbstractMessageListenerContainer.java:1219) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.stop(AbstractMessageListenerContainer.java:1192) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.doStop(AmqpInboundChannelAdapter.java:150) ~[spring-integration-amqp-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:179) ~[spring-integration-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.stop(DefaultBinding.java:119) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:147) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:274) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.unbindInputs(BindableProxyFactory.java:268) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:62) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:55) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:33) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:72) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:33) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1007) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:935) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
```
## Can anyone help me with this?

**Comment by garyrussell** [comment]
Please read about GitHub Markdown.

Please provide more information, including your `application.yml/properties` and exactly how you are stopping the application.

It appears the binding is being stopped after the connection factory is destroyed, which is odd.

After analysis, it is possible that this issue will have to be moved the spring-cloud-stream-binder-rabbit.

**Comment by davidarce** [comment]
Hi @garyrussell thanks for your answer

This is my application.yml

```
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        armIn:
          destination: reservations
          group: checkoutbooking
          binder: arm-binder
          content-type: application/x-java-object
        reservationStatusOut:
          destination: reservations
          binder: checkout-binder
        bookOut:
          destination: checkout-booking
          binder: booking-binder

      kafka:
        binder:
          brokers: kafka-events
          zkNodes: kafka-events
          headers: type

      binders:
        arm-binder:
          type: rabbit
          inheritEnvironment: false
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: --rabbitmq--
                port: 5672
                username: --private--
                password: --private--
                virtual-host: arm
        checkout-binder:
          type: rabbit
          inheritEnvironment: false
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: --rabbitmq--
                port: 5672
                username: --private--
                password: --private--
                virtual-host: checkout
        booking-binder:
          type: kafka
          inheritEnvironment: true
          defaultCandidate: false

      rabbit:
        bindings:
          reservationStatusOut:
            producer:
              bindingRoutingKey: reservation_status
              routingKeyExpression: '"reservation_status"'
          armIn:
            consumer:
              declareExchange: false
              exchangeType: topic
```

## full stacktrace when exit console in Intellij IDEA

```
08:59:02.377 [Thread-13] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@42a198dd: startup date [Fri Jan 25 08:58:52 COT 2019]; root of context hierarchy
08:59:02.378 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.379 [Thread-14] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4414ee28: startup date [Fri Jan 25 08:58:56 COT 2019]; root of context hierarchy
08:59:02.379 [Thread-15] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1c32886a: startup date [Fri Jan 25 08:58:42 COT 2019]; root of context hierarchy
08:59:02.390 [Thread-15] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4c140b12: startup date [Fri Jan 25 08:58:54 COT 2019]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1c32886a
08:59:02.390 [Thread-14] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
08:59:02.390 [Thread-13] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
08:59:02.391 [Thread-14] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 0
08:59:02.393 [Thread-13] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 0
08:59:02.397 [Thread-15] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483647
08:59:02.397 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.398 [Thread-15] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147483547
08:59:02.398 [Thread-15] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 2147482647
08:59:02.404 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.406 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.408 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.410 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.411 [RestConnetorShutdownHook] INFO  c.almundo.commons.rest.RestConnector - Shutting down rest connector
08:59:02.679 [Thread-15] WARN  o.s.c.s.DefaultLifecycleProcessor - Failed to stop bean 'inputBindingLifecycle'
org.springframework.amqp.AmqpApplicationContextClosedException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:622) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:578) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$600(CachingConnectionFactory.java:99) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1053) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at com.sun.proxy.$Proxy166.basicCancel(Unknown Source) ~[na:na]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.basicCancel(BlockingQueueConsumer.java:399) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doShutdown(SimpleMessageListenerContainer.java:521) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.shutdown(AbstractMessageListenerContainer.java:1100) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doStop(AbstractMessageListenerContainer.java:1219) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.stop(AbstractMessageListenerContainer.java:1192) ~[spring-rabbit-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.doStop(AmqpInboundChannelAdapter.java:150) ~[spring-integration-amqp-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.integration.endpoint.AbstractEndpoint.stop(AbstractEndpoint.java:179) ~[spring-integration-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.stop(DefaultBinding.java:119) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinding.unbind(DefaultBinding.java:147) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.unbindConsumers(BindingService.java:274) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.unbindInputs(BindableProxyFactory.java:268) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStopWithBindable(InputBindingLifecycle.java:62) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:55) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:33) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.stop(AbstractBindingLifecycle.java:72) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.stop(InputBindingLifecycle.java:33) ~[spring-cloud-stream-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1007) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:935) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]

```
## My class configuration:

```java
@Configuration
@EnableBinding(value = {ReservationStatusProcessor.class, BookProcessor.class})
public class StreamConfiguration {

    @Bean
    public DataSource<ReservationStatusProcessor> reservationStatusDataSource(ReservationStatusProcessor reservationStatusOut) {
        return new DataSource<>(reservationStatusOut);
    }

    @Bean
    public DataSource<BookProcessor> bookDataSource(BookProcessor bookOut) {
        return new DataSource<>(bookOut);
    }
}
```
 ## And here is my listener

```java

@EnableBinding(ArmSink.class)
@Component
public class ArmStreamListener {
    private static final Logger LOGGER = LoggerFactory.getLogger(ArmStreamListener.class);

    private final ArmEventsService armEventsService;
    private final ReservationStatusSource reservationStatusSource;

    public ArmStreamListener(ArmEventsService armEventsService,
                             ReservationStatusSource reservationStatusSource) {
        this.armEventsService = armEventsService;
        this.reservationStatusSource = reservationStatusSource;
    }


    @StreamListener(target = ArmSink.INPUT, condition = "headers['EVENT'] == 'PAYED' or headers['EVENT'] == 'PAYMENT_ERROR'")
    public void recieveArmEvent(ReservationMessage message, @Header("EVENT") String event) {
        LOGGER.info("Receiving Arm Event [{}] - [{}]", event, message.getId());

        if (message != null) {
            SourceMessage sourceMessage = message.getSource();

            ArmEventDTO armEvent = ArmEventDTO.builder()
                    .armId(message.getId())
                    .metadata(buildMetadata(sourceMessage))
                    .status(ArmReservationStatus.valueOf(event))
                    .build();

            armEventsService.process(armEvent)
                    .ifPresent(e -> reservationStatusSource.sendStatusChangedEvent(e));
            LOGGER.info("ArmEvent has been processed [{}]", armEvent);
        }
    }


    private Metadata buildMetadata(SourceMessage sourceMessage) {
        return Metadata.builder()
                .brand(sourceMessage.getBrand())
                .site(sourceMessage.getCountry())
                .channel(sourceMessage.getChannel())
                .build();
    }
}

```

##

**Comment by garyrussell** [comment]
If it's easily reproducible, can you do so with DEBUG logging enabled so we can see when the connection factory is being destroyed? That should not happen until the bindings are stopped.

Perhaps post to pastebin or a github gist instead of inline here.

**Comment by garyrussell** [comment]
For the benefit of future readers, would you care to explain what the problem was?

Thanks.
