### ISSUE TITLE
MessageProperties.hashCode() throws NPE if correlationId is null

### ISSUE THREAD

**Issue by sotcsa** [spring-projects/spring-amqp#918]
**Affects Version(s):** 2.1.4

---

## Bug report
Related issue https://github.com/spring-projects/spring-amqp/issues/730 
Related task: https://jira.spring.io/browse/AMQP-645
The hashCode() throws exception if correlationId is null

Example test:
```
    Set set = new HashSet();
    set.add(new MessageProperties());
```
```
Exception in thread "main" java.lang.NullPointerException
	at org.springframework.amqp.core.MessageProperties.hashCode(MessageProperties.java:545)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at test.Test.main(Test.java:12)
```

**Comment by artembilan** [comment]
Would you mind to provide a fix via contribution: https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc ?

Thanks

**Comment by sotcsa** [comment]
Done, I hope it is in good shape

**Comment by artembilan** [comment]
Closed via: https://github.com/spring-projects/spring-amqp/commit/012df67ce3d811f4a7050cdf433087f7fce22e8d
