### ISSUE TITLE
SimpleMessageListenerContainer.redeclareElementsIfNecessary() throws NullPointerException in spring-rabbit-1.3.6

### ISSUE THREAD

**Issue by akhishukla23** [spring-projects/spring-amqp#924]
This happens during startup while using base spring 4.0.9.

org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer,null,SimpleAsyncTaskExecutor-1,access$200():78,Failed to check/redeclare auto-delete queue(s).
java.lang.NullPointerException: null
                at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:893) [spring-rabbit.jar:na]
                at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$200(SimpleMessageListenerContainer.java:78) [spring-rabbit.jar:na]
                at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1008) [spring-rabbit.jar:na]
                at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

However when I upgraded to spring5 and eventually upgrading spring-rabbit to 2.0.3 version this issue is not seen.

**Comment by artembilan** [comment]
The Spring AMQP `1.3.6` is too old and already out of support. For Spring 4.x base line we recommend to upgrade to the latest `1.7.x`: https://spring.io/projects/spring-amqp#learn

**Comment by akhishukla23** [comment]
Thanks, I will try upgrading just AMQP to latest 1.7.x and see this issue goes away while keeping base spring to 4.0.9

**Comment by garyrussell** [comment]
Closing due to lack of activity; please open a new issue if you are still having issues.
