### ISSUE TITLE
NPE in PublisherCallbackChannelImpl when the channel fails to be configured

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-amqp#933]
**Affects Version(s):** 2.1.4

---
Being an AMQP/RabbitMQ newbie, I have misconfigured my client, as far as I understand, by using transacted mode and enabling publisher confirms.

The problem that I'm reporting is that it is seems the error publisher isn't properly configured, so it cannot handle the `ShutdownSignalException` because the `executor` is not yet set in the `PublisherCallbackChannelImpl`:

```
public PublisherCallbackChannelImpl(Channel delegate, ExecutorService executor) {
	Assert.notNull(executor, "'executor' must not be null");
	delegate.addShutdownListener(this);
	this.delegate = delegate;
	this.executor = executor;
}
```
This constructor gets invoked, with the generated `executor`, then `delegate.addShutdownListener(this)`, but since `shutdownCause` is not null, the listener gets invoked before the executor parameter being assigned to the field.

```
java.lang.NullPointerException: null
  at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:828) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:1107) ~[?:2.1.4.RELEASE]
  at com.rabbitmq.client.impl.ShutdownNotifierComponent.addShutdownListener(ShutdownNotifierComponent.java:55) ~[?:?]
  at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.<init>(PublisherCallbackChannelImpl.java:128) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:665) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:637) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:607) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceFactory.createChannel(ConnectionFactoryUtils.java:299) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:147) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:93) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2053) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$execute$13(RabbitTemplate.java:2024) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[?:?]
  at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[?:?]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2023) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:982) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:1048) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:1020) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
```

The fix should probably be to move `delegate.addShutdownListener(this);` after the `executor` field gets assigned.

This is the root cause:
```
ERROR [o.s.a.r.c.CachingConnectionFactory] - Could not configure the channel to receive publisher confirms
java.io.IOException: null
  at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126) ~[?:?]
  at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122) ~[?:?]
  at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:144) ~[?:?]
  at com.rabbitmq.client.impl.ChannelN.confirmSelect(ChannelN.java:1552) ~[?:?]
  at com.rabbitmq.client.impl.ChannelN.confirmSelect(ChannelN.java:52) ~[?:?]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:657) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:637) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:607) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceFactory.createChannel(ConnectionFactoryUtils.java:299) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:147) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:93) ~[?:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2053) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.lambda$execute$13(RabbitTemplate.java:2024) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[?:?]
  at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[?:?]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2023) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:982) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:1048) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
  at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:1020) ~[spring-rabbit-2.1.4.RELEASE.jar:2.1.4.RELEASE]
```

**Comment by andrei-ivanov** [comment]
Wow, amazing job, thank you :)
