### ISSUE TITLE
JDK11 + windows classloader problem

### ISSUE THREAD

**Issue by vetesii** [spring-projects/spring-amqp#967]
**Affects Version(s):** \2.1.5

We switched from java 8 to java 11, and run into some problem:

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: org.springframework.amqp.rabbit.connection.ChannelProxy referenced from a method is not visible from class loader
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[na:na]
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: java.lang.IllegalArgumentException: org.springframework.amqp.rabbit.connection.ChannelProxy referenced from a method is not visible from class loader
    at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858) ~[na:na]
    at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:681) ~[na:na]
    at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627) ~[na:na]
    at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635) ~[na:na]
    at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415) ~[na:na]
    at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[na:na]
    at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[na:na]
    at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:413) ~[na:na]
    at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006) ~[na:na]
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:619) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2079) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2047) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.doSendAndReceiveWithTemporary(RabbitTemplate.java:1775) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.doSendAndReceive(RabbitTemplate.java:1765) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveRaw(RabbitTemplate.java:1731) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveAsType(RabbitTemplate.java:1702) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitOperations.convertSendAndReceiveAsType(RabbitOperations.java:355) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceiveAsType(RabbitTemplate.java:1646) ~[spring-rabbit-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
    at hu.vetesii.mqerror.Application.lambda$sendMessage$0(Application.java:77) ~[classes!/:0.0.2]
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
    ... 6 common frames omitted
```

This commit ("Use Context CL whenever it is applicable") modified the ChannelCachingConnectionProxy class: https://github.com/spring-projects/spring-amqp/commit/787dfa00f80d2ed33ffe40b9a0431652c72acc15#diff-a0e92789e5f983fc54cff7542a274e4dL620

I don't dig deeper, but with its original classloader  

```
-        return (ChannelProxy) Proxy.newProxyInstance(ClassUtils.getDefaultClassLoader(),
+        return (ChannelProxy) Proxy.newProxyInstance(ChannelProxy.class.getClassLoader(),
```

it seems fine with java 11.

This problem a little bit strange because:

* Windows + zulu JDK8 + complete spring-boot jar-> Good
* Windows + zulu JDK11 + complete spring-boot jar -> Error
* Windows + (https://github.com/ojdkbuild/ojdkbuild) open JDK11 + complete spring-boot jar -> Error
* Windows + zulu JDK11 + eclipse inner build -> Good
* Windows + zulu JDK11 + complete spring-boot jar -> Error
* Windows + adopt JDK11 + complete spring-boot jar -> Error
* Ubuntu + adoptJDK 11 + complete spring-boot jar, Netbeans/STS/Eclipse inner build -> Good

complete spring-boot jar: whole maven build and run with `java -jar ...`

IDE build: whatever the IDE is doing, but in these scenario a Main class is not the org.springframework.boot.loader.JarLauncher class, so LaunchedURLClassLoader doesn't get a big role

As I mentioned, we don't dig deeper than above, but we have a minimal test project for this: https://github.com/vetesii/mq-error1

There was a similar issue: https://github.com/spring-projects/spring-amqp/pull/898

**Comment by artembilan** [comment]
@vetesii ,

Is this PR #968 what you think about the issue?

I really don't see reason in that place to move a proxy into a different classloader and the `ChannelProxy`-specif one is fully enough as you have pointed.

Thank you!

**Comment by vetesii** [comment]
@artembilan ,

Yes, the classloader change eliminated the problem. Thank you very much!

**Comment by renatojava** [comment]
The same problem with springboot 2.1.6 springdata mongo dbref
java.lang.IllegalArgumentException: org.springframework.data.mongodb.core.convert.LazyLoadingProxy referenced from a method is not visible from class loader

**Comment by garyrussell** [comment]
Mongodb has nothing to do with this project; you should open an issue over there.
